package ec.edu.monster.modelo;
// Generated 04-ago-2020 1:40:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aeronave generated by hbm2java
 */
public class Aeronave  implements java.io.Serializable {


     private int idaeronave;
     private String nombreaer;
     private String modeloaer;
     private Integer capacidadtotalaer;
     private Set vuelos = new HashSet(0);

    public Aeronave() {
    }

	
    public Aeronave(int idaeronave) {
        this.idaeronave = idaeronave;
    }
    public Aeronave(int idaeronave, String nombreaer, String modeloaer, Integer capacidadtotalaer, Set vuelos) {
       this.idaeronave = idaeronave;
       this.nombreaer = nombreaer;
       this.modeloaer = modeloaer;
       this.capacidadtotalaer = capacidadtotalaer;
       this.vuelos = vuelos;
    }
   
    public int getIdaeronave() {
        return this.idaeronave;
    }
    
    public void setIdaeronave(int idaeronave) {
        this.idaeronave = idaeronave;
    }
    public String getNombreaer() {
        return this.nombreaer;
    }
    
    public void setNombreaer(String nombreaer) {
        this.nombreaer = nombreaer;
    }
    public String getModeloaer() {
        return this.modeloaer;
    }
    
    public void setModeloaer(String modeloaer) {
        this.modeloaer = modeloaer;
    }
    public Integer getCapacidadtotalaer() {
        return this.capacidadtotalaer;
    }
    
    public void setCapacidadtotalaer(Integer capacidadtotalaer) {
        this.capacidadtotalaer = capacidadtotalaer;
    }
    public Set getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(Set vuelos) {
        this.vuelos = vuelos;
    }




}


