package ec.edu.monster.modelo;
// Generated 04-ago-2020 1:40:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Descuento generated by hbm2java
 */
public class Descuento  implements java.io.Serializable {


     private int iddescuento;
     private String nombredes;
     private String descripciondes;
     private BigDecimal valordes;
     private Set pedidos = new HashSet(0);

    public Descuento() {
    }

	
    public Descuento(int iddescuento) {
        this.iddescuento = iddescuento;
    }
    public Descuento(int iddescuento, String nombredes, String descripciondes, BigDecimal valordes, Set pedidos) {
       this.iddescuento = iddescuento;
       this.nombredes = nombredes;
       this.descripciondes = descripciondes;
       this.valordes = valordes;
       this.pedidos = pedidos;
    }
   
    public int getIddescuento() {
        return this.iddescuento;
    }
    
    public void setIddescuento(int iddescuento) {
        this.iddescuento = iddescuento;
    }
    public String getNombredes() {
        return this.nombredes;
    }
    
    public void setNombredes(String nombredes) {
        this.nombredes = nombredes;
    }
    public String getDescripciondes() {
        return this.descripciondes;
    }
    
    public void setDescripciondes(String descripciondes) {
        this.descripciondes = descripciondes;
    }
    public BigDecimal getValordes() {
        return this.valordes;
    }
    
    public void setValordes(BigDecimal valordes) {
        this.valordes = valordes;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


