package ec.edu.monster.modelo;
// Generated 04-ago-2020 1:40:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int idempleado;
     private String nombresemp;
     private String apellidosemp;
     private String cedulaemp;
     private String telfemp;
     private String correoemp;
     private String cargoemp;
     private Date fechanacimiento;
     private Set usuarios = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int idempleado) {
        this.idempleado = idempleado;
    }
    public Empleado(int idempleado, String nombresemp, String apellidosemp, String cedulaemp, String telfemp, String correoemp, String cargoemp, Date fechanacimiento, Set usuarios) {
       this.idempleado = idempleado;
       this.nombresemp = nombresemp;
       this.apellidosemp = apellidosemp;
       this.cedulaemp = cedulaemp;
       this.telfemp = telfemp;
       this.correoemp = correoemp;
       this.cargoemp = cargoemp;
       this.fechanacimiento = fechanacimiento;
       this.usuarios = usuarios;
    }
   
    public int getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(int idempleado) {
        this.idempleado = idempleado;
    }
    public String getNombresemp() {
        return this.nombresemp;
    }
    
    public void setNombresemp(String nombresemp) {
        this.nombresemp = nombresemp;
    }
    public String getApellidosemp() {
        return this.apellidosemp;
    }
    
    public void setApellidosemp(String apellidosemp) {
        this.apellidosemp = apellidosemp;
    }
    public String getCedulaemp() {
        return this.cedulaemp;
    }
    
    public void setCedulaemp(String cedulaemp) {
        this.cedulaemp = cedulaemp;
    }
    public String getTelfemp() {
        return this.telfemp;
    }
    
    public void setTelfemp(String telfemp) {
        this.telfemp = telfemp;
    }
    public String getCorreoemp() {
        return this.correoemp;
    }
    
    public void setCorreoemp(String correoemp) {
        this.correoemp = correoemp;
    }
    public String getCargoemp() {
        return this.cargoemp;
    }
    
    public void setCargoemp(String cargoemp) {
        this.cargoemp = cargoemp;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


