package ec.edu.monster.modelo;
// Generated 04-ago-2020 1:40:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FormacionParacaidista generated by hbm2java
 */
public class FormacionParacaidista  implements java.io.Serializable {


     private int idforpar;
     private String nombrecurso;
     private Date fechainiciocurso;
     private Date fechafincurso;
     private String lugarcurso;
     private Set paracaidistas = new HashSet(0);

    public FormacionParacaidista() {
    }

	
    public FormacionParacaidista(int idforpar) {
        this.idforpar = idforpar;
    }
    public FormacionParacaidista(int idforpar, String nombrecurso, Date fechainiciocurso, Date fechafincurso, String lugarcurso, Set paracaidistas) {
       this.idforpar = idforpar;
       this.nombrecurso = nombrecurso;
       this.fechainiciocurso = fechainiciocurso;
       this.fechafincurso = fechafincurso;
       this.lugarcurso = lugarcurso;
       this.paracaidistas = paracaidistas;
    }
   
    public int getIdforpar() {
        return this.idforpar;
    }
    
    public void setIdforpar(int idforpar) {
        this.idforpar = idforpar;
    }
    public String getNombrecurso() {
        return this.nombrecurso;
    }
    
    public void setNombrecurso(String nombrecurso) {
        this.nombrecurso = nombrecurso;
    }
    public Date getFechainiciocurso() {
        return this.fechainiciocurso;
    }
    
    public void setFechainiciocurso(Date fechainiciocurso) {
        this.fechainiciocurso = fechainiciocurso;
    }
    public Date getFechafincurso() {
        return this.fechafincurso;
    }
    
    public void setFechafincurso(Date fechafincurso) {
        this.fechafincurso = fechafincurso;
    }
    public String getLugarcurso() {
        return this.lugarcurso;
    }
    
    public void setLugarcurso(String lugarcurso) {
        this.lugarcurso = lugarcurso;
    }
    public Set getParacaidistas() {
        return this.paracaidistas;
    }
    
    public void setParacaidistas(Set paracaidistas) {
        this.paracaidistas = paracaidistas;
    }




}


