package ec.edu.monster.modelo;
// Generated 04-ago-2020 1:40:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private int idperfil;
     private String nombreper;
     private String estadoper;
     private String estadoper2;
     private Date fechacreacionper;
     private Date fechamodper;
     private Set permisos = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(int idperfil) {
        this.idperfil = idperfil;
    }
    public Perfil(int idperfil, String nombreper, String estadoper, String estadoper2, Date fechacreacionper, Date fechamodper, Set permisos, Set usuarios) {
       this.idperfil = idperfil;
       this.nombreper = nombreper;
       this.estadoper = estadoper;
       this.estadoper2 = estadoper2;
       this.fechacreacionper = fechacreacionper;
       this.fechamodper = fechamodper;
       this.permisos = permisos;
       this.usuarios = usuarios;
    }
   
    public int getIdperfil() {
        return this.idperfil;
    }
    
    public void setIdperfil(int idperfil) {
        this.idperfil = idperfil;
    }
    public String getNombreper() {
        return this.nombreper;
    }
    
    public void setNombreper(String nombreper) {
        this.nombreper = nombreper;
    }
    public String getEstadoper() {
        return this.estadoper;
    }
    
    public void setEstadoper(String estadoper) {
        this.estadoper = estadoper;
    }
    public String getEstadoper2() {
        return this.estadoper2;
    }
    
    public void setEstadoper2(String estadoper2) {
        this.estadoper2 = estadoper2;
    }
    public Date getFechacreacionper() {
        return this.fechacreacionper;
    }
    
    public void setFechacreacionper(Date fechacreacionper) {
        this.fechacreacionper = fechacreacionper;
    }
    public Date getFechamodper() {
        return this.fechamodper;
    }
    
    public void setFechamodper(Date fechamodper) {
        this.fechamodper = fechamodper;
    }
    public Set getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set permisos) {
        this.permisos = permisos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


