package ec.edu.monster.modelo;
// Generated 04-ago-2020 1:40:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Recurso generated by hbm2java
 */
public class Recurso  implements java.io.Serializable {


     private Integer idrecurso;
     private Recurso recurso;
     private String nombrerec;
     private String paginarec;
     private String iconorec;
     private Integer indicerec;
     private String estadorec;
     private Set recursos = new HashSet(0);
     private Set permisos = new HashSet(0);

    public Recurso() {
    }

    public Recurso(Recurso recurso, String nombrerec, String paginarec, String iconorec, Integer indicerec, String estadorec, Set recursos, Set permisos) {
       this.recurso = recurso;
       this.nombrerec = nombrerec;
       this.paginarec = paginarec;
       this.iconorec = iconorec;
       this.indicerec = indicerec;
       this.estadorec = estadorec;
       this.recursos = recursos;
       this.permisos = permisos;
    }
   
    public Integer getIdrecurso() {
        return this.idrecurso;
    }
    
    public void setIdrecurso(Integer idrecurso) {
        this.idrecurso = idrecurso;
    }
    public Recurso getRecurso() {
        return this.recurso;
    }
    
    public void setRecurso(Recurso recurso) {
        this.recurso = recurso;
    }
    public String getNombrerec() {
        return this.nombrerec;
    }
    
    public void setNombrerec(String nombrerec) {
        this.nombrerec = nombrerec;
    }
    public String getPaginarec() {
        return this.paginarec;
    }
    
    public void setPaginarec(String paginarec) {
        this.paginarec = paginarec;
    }
    public String getIconorec() {
        return this.iconorec;
    }
    
    public void setIconorec(String iconorec) {
        this.iconorec = iconorec;
    }
    public Integer getIndicerec() {
        return this.indicerec;
    }
    
    public void setIndicerec(Integer indicerec) {
        this.indicerec = indicerec;
    }
    public String getEstadorec() {
        return this.estadorec;
    }
    
    public void setEstadorec(String estadorec) {
        this.estadorec = estadorec;
    }
    public Set getRecursos() {
        return this.recursos;
    }
    
    public void setRecursos(Set recursos) {
        this.recursos = recursos;
    }
    public Set getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set permisos) {
        this.permisos = permisos;
    }




}


