package ec.edu.monster.modelo;
// Generated 04-ago-2020 1:40:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Salto generated by hbm2java
 */
public class Salto  implements java.io.Serializable {


     private int idsalto;
     private String tiposalto;
     private Set pedidos = new HashSet(0);

    public Salto() {
    }

	
    public Salto(int idsalto) {
        this.idsalto = idsalto;
    }
    public Salto(int idsalto, String tiposalto, Set pedidos) {
       this.idsalto = idsalto;
       this.tiposalto = tiposalto;
       this.pedidos = pedidos;
    }
   
    public int getIdsalto() {
        return this.idsalto;
    }
    
    public void setIdsalto(int idsalto) {
        this.idsalto = idsalto;
    }
    public String getTiposalto() {
        return this.tiposalto;
    }
    
    public void setTiposalto(String tiposalto) {
        this.tiposalto = tiposalto;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


