package ec.edu.monster.modelo;
// Generated 04-ago-2020 1:40:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vuelo generated by hbm2java
 */
public class Vuelo  implements java.io.Serializable {


     private Integer idvuelo;
     private Aeronave aeronave;
     private Piloto piloto;
     private Date horasalida;
     private Date horallegada;
     private Integer capacidadpersonas;
     private Set detalleVuelos = new HashSet(0);

    public Vuelo() {
    }

    public Vuelo(Aeronave aeronave, Piloto piloto, Date horasalida, Date horallegada, Integer capacidadpersonas, Set detalleVuelos) {
       this.aeronave = aeronave;
       this.piloto = piloto;
       this.horasalida = horasalida;
       this.horallegada = horallegada;
       this.capacidadpersonas = capacidadpersonas;
       this.detalleVuelos = detalleVuelos;
    }
   
    public Integer getIdvuelo() {
        return this.idvuelo;
    }
    
    public void setIdvuelo(Integer idvuelo) {
        this.idvuelo = idvuelo;
    }
    public Aeronave getAeronave() {
        return this.aeronave;
    }
    
    public void setAeronave(Aeronave aeronave) {
        this.aeronave = aeronave;
    }
    public Piloto getPiloto() {
        return this.piloto;
    }
    
    public void setPiloto(Piloto piloto) {
        this.piloto = piloto;
    }
    public Date getHorasalida() {
        return this.horasalida;
    }
    
    public void setHorasalida(Date horasalida) {
        this.horasalida = horasalida;
    }
    public Date getHorallegada() {
        return this.horallegada;
    }
    
    public void setHorallegada(Date horallegada) {
        this.horallegada = horallegada;
    }
    public Integer getCapacidadpersonas() {
        return this.capacidadpersonas;
    }
    
    public void setCapacidadpersonas(Integer capacidadpersonas) {
        this.capacidadpersonas = capacidadpersonas;
    }
    public Set getDetalleVuelos() {
        return this.detalleVuelos;
    }
    
    public void setDetalleVuelos(Set detalleVuelos) {
        this.detalleVuelos = detalleVuelos;
    }




}


