package ec.edu.saltos.config;

/**
 *
 * @author guffenix
 */
public enum EstadosConfig {
    
    //    AMBIENTES
    AMBIENTE_DEV("DESARROLLO - SISTEMA DE SALTOS", "DEV", 0),
    AMBIENTE_PRO("PRODUCCION - SISTEMA DE SALTOS", "PRO", 0),
    AMBIENTE_QA("PREPRODUCCION - SISTEMA DE SALTOS", "QA", 0),

    //    PERFIL
    PERFIL_SUPERADMIN("PERFIL DE SUPER ADMINISTRADOR ", "PSA", 0),
    PERFIL_ADMINISTRADOR("PERFIL DE ADMINISTRADOR ", "PAD", 0),
    PERFIL_USUARIO("PERFIL DE USUARIO", "PUS", 0),
    //    ESTATUS OPCIONES
    OPCION_EST_ACTIVADO("OPCION ACTIVADA","OAC",0),
    OPCION_EST_DESACTIVADO("OPCION DESACTIVADA","ODE",0),
    //    ESTATUS OPCIONES PERFIL
    OPCION_PER_ACTIVADA("OPCION PERFIL ACTIVADA","OPA",0),
    OPCION_PER_DESACTIVADA("OPCION PERFIL DESACTIVADA","OPD",0),
    //    ESTATUS PERFIL
    PERFIL_EST_ACTIVADO("PERFIL ACTIVADA","PAC",0),
    PERFIL_EST_DESACTIVADO("PERFIL DESACTIVADA","PDE",0),
    PERFIL_EST_ARCHIVADO("PERFIL ARCHIVADO","PAR",0),
    //    ESTATUS 2 PERFIL
    PERFIL_EST2_ADMINISTRADOR("PERFIL TIPO ADMINISTRADOR","PTA",0),
    PERFIL_EST2_USUARIO("PERFIL TIPO USUARIO","PTU",0),
    //    ESTATUS USUARIO ACCESO
    USR_ACC_ACTIVADO("ACTIVADO","UAA",0),
    USR_ACC_DESACTIVADO("DESACTIVADO","UAD",0),
    USR_ACC_ARCHIVADO("ARCHIVADO","UAR",0),
    USR_ACC_ESPERA("EN ESPERA","UAE",0),
    USR_ACC_SUPER_ADM("USUARIO SUPER ADMIN","USA",0),
    
    //    ESTATUS PERSONA
    PERSONA_EST_ACTIVADO("ACTIVADO","PEC",0),
    PERSONA_EST_DESACTIVADO("DESACTIVADO","PED",0),
    PERSONA_EST_ARCHIVADO("ARCHIVADO","PEA",0),
    PERSONA_EST_ESPERA("EN ESPERA","PEE",0),
    
    //    OPCION
    OPCION_CATEGORIA("Módulo", "MOD", 0),
    OPCION_PLANTILLA("Aplicación", "APP", 0),
    OPCION_ORIGEN("Raíz", "ORG", 0),
    OPCION_SIN_URL("OPCION SIN RUL", "NOURL", 0),
    OPCION_CONSTRUCCION("OPCION EN CONSTRUCCION", "/usr/pagina-construccion", 0),
    //    CLAVE
    CLAVE_VACIA("CLAVE VACIA","CVA",0),
    CLAVE_USUARIO("CLAVE TIPO USUARIO", "USR", 0),
    CLAVE_REENVIADA("CLAVE TIPO REENVIO", "CAM", 0),
    CLAVE_CADUCADA("CLAVE CADUCADA", "CCA", 0),
    CLAVE_ERRONEA("CLAVE ERRONEA", "ERR", 0),
    CLAVE_ACTIVA("CLAVE ACTIVO", "ACT", 0),
    //    CORREO
    HOST_CORREO_NOTIFICACION("HOST_CORREO_NOTIFICACION", "", 0),
    PUERTO_CORREO_NOTIFICACION("PUERTO_CORREO_NOTIFICACION", "587", 0),
    USUARIO_CORREO_NOTIFICACION("USUARIO_CORREO_NOTIFICACION", "kataday@espe.edu.ec", 0),
    CLAVE_CORREO_NOTIFICACION("PASSWORD_CORREO_NOTIFICACION", "", 0),
    CUENTA_CORREO_NOTIFICACION("CUENTA_CORREO_NOTIFICACION", "", 0),
    CUENTA_DESACTIVADA("CUENTA DESACTIVADA", "CDE", 0),
    MODO_NOTIFICACION_CORREO("CUENTA CORREO", "1", 0),
    //    PREFERENCIAS APP
    APP_TEMA_USER("TEMA AZUL OSCURO", "azul-claro", 0),
    APP_LAYOUT_USER("CAPAS AZUL OSCURO, BOTONES, ETC", "azul-claro", 0),
    APP_FORMAT_FECHA_SIMPLE("FORMATO DE SOLO FECHA","dd-MM-yyyy",0),
    APP_FORMAT_FECHA_COMPUESTO_MES("FORMATO DE SOLO FECHA","dd MMMM yyyy",0),
    APP_FORMAT_FECHA_COMPUESTO_DIA_MES("FORMATO DE SOLO FECHA","E, dd MMM yyyy",0),
    APP_FORMAT_HORA_SIMPLE("FORMATO DE SOLO HORA","HH:mm:ss",0),
    APP_FORMAT_HORA_AM_PM("FORMATO DE SOLO HORA","hh:mm a",0),
    //    EMPRESA
    NOMBRE_EMPRESA("LOS GARRAPATEROS","LOS GARRAPATEROS",0),
    HORA_INICIO_ATENCION("10:00 A.M.","10:00:00",0),
    DIAS_ATENCION("FIN DE SEMANA","VIERNES,SABADO,DOMINGO",0),
    DESCUENTO__LIBRE_2T_1P("2 TANDEM - 1 SALTO LIBRE","",40),
    DESCUENTO__LIBRE_1T_3P("1 TANDEM - 3 SALTOS LIBRES","",50),
    DESCUENTO__LIBRE_5P("5 SALTOS LIBRES","",60),
    NUM_FACTURA_INICIAL("Numero de factura inicial","2001001020",0),
    //Versionamiento
    VERSION_APP("Versión del Aplicativo", "1.5.0", 0),
    TIEMPO_SESION("", "", 1201_000),
    TIEMPO_SESION_ADM("", "", 601_000),
    TIEMPO_SESION_SUPER("", "", 601_000),
    INDICE_PING("REALIZAR PING", "PING", 1),
    VISOR_PAG1("ID PAGINA 0", "PG1", 0),
    VISOR_PAG2("ID PAGINA 1", "PG2", 1),
    CEDULA_DEFAULT("CEDULA TEMPORAL PARA CREACION", "1000000000", 1000000000),
    //    VALORES DEFAULT CLAVE
    CARACTERES_MAX_CLAVES("MAXIMO DE CARACTERES EN LA CLAVE", "", 18),
    CARACTERES_MIN_CLAVES("MINIMO DE CARACTERES EN LA CLAVE", "", 6),
    CARACTERES_ALFANUMERICOS("CARACTERES ALFANUMERICOS EN LA CLAVE", "", 1),
    CARACTERES_MAYUS("CARACTERES MAYUS EN LA CLAVE", "", 1),
    CARACTERES_MINUS("CARACTERES MINUS EN LA CLAVE", "", 1),
    CARACTERES_ESPECIALES("CARACTERES ESPECIALES EN LA CLAVE", "", 1),
    CARACTERES_ESPECIALES_PERMITIDOS("CARACTERES ESPECIALES DE CLAVES", ",.-_", 1),
    NUMERO_CAMBIOS_POR_DIA("NUMERO DE CAMBIOS AL DIA", "", 5),
    INTENTOS_FALLIDOS("INTENTOS DE LOGGEO PERMITIDO", "", 3),
    ULTIMA_CLAVE("ULTIMA CLAVE", "", 1);

    private final String descripcion;
    private final String codigo;
    private final Integer id;

    EstadosConfig(String _descripcion, String _codigo, Integer _id) {
        this.descripcion = _descripcion;
        this.codigo = _codigo;
        this.id = _id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public String getCodigo() {
        return codigo;
    }

    public Integer getId() {
        return id;
    }

}
