package ec.edu.saltos.modelo;
// Generated 31-ago-2020 17:42:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Aeronave generated by hbm2java
 */
public class Aeronave  implements java.io.Serializable {


     private int idAeronave;
     private String aerNombre;
     private String aerModelo;
     private Integer aerCapacidadTotal;
     private Date aerFechaCreacion;
     private Date aerFechaMod;
     private Set<Vuelo> vuelos = new HashSet<Vuelo>(0);

    public Aeronave() {
    }

	
    public Aeronave(int idAeronave) {
        this.idAeronave = idAeronave;
    }
    public Aeronave(int idAeronave, String aerNombre, String aerModelo, Integer aerCapacidadTotal, Date aerFechaCreacion, Date aerFechaMod, Set<Vuelo> vuelos) {
       this.idAeronave = idAeronave;
       this.aerNombre = aerNombre;
       this.aerModelo = aerModelo;
       this.aerCapacidadTotal = aerCapacidadTotal;
       this.aerFechaCreacion = aerFechaCreacion;
       this.aerFechaMod = aerFechaMod;
       this.vuelos = vuelos;
    }
   
    public int getIdAeronave() {
        return this.idAeronave;
    }
    
    public void setIdAeronave(int idAeronave) {
        this.idAeronave = idAeronave;
    }
    public String getAerNombre() {
        return this.aerNombre;
    }
    
    public void setAerNombre(String aerNombre) {
        this.aerNombre = aerNombre;
    }
    public String getAerModelo() {
        return this.aerModelo;
    }
    
    public void setAerModelo(String aerModelo) {
        this.aerModelo = aerModelo;
    }
    public Integer getAerCapacidadTotal() {
        return this.aerCapacidadTotal;
    }
    
    public void setAerCapacidadTotal(Integer aerCapacidadTotal) {
        this.aerCapacidadTotal = aerCapacidadTotal;
    }
    public Date getAerFechaCreacion() {
        return this.aerFechaCreacion;
    }
    
    public void setAerFechaCreacion(Date aerFechaCreacion) {
        this.aerFechaCreacion = aerFechaCreacion;
    }
    public Date getAerFechaMod() {
        return this.aerFechaMod;
    }
    
    public void setAerFechaMod(Date aerFechaMod) {
        this.aerFechaMod = aerFechaMod;
    }
    public Set<Vuelo> getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(Set<Vuelo> vuelos) {
        this.vuelos = vuelos;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 41 * hash + this.idAeronave;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Aeronave other = (Aeronave) obj;
        if (this.idAeronave != other.idAeronave) {
            return false;
        }
        return true;
    }




}


