package ec.edu.saltos.modelo;
// Generated 31-ago-2020 17:42:00 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * CabeceraFactura generated by hbm2java
 */
public class CabeceraFactura  implements java.io.Serializable {


     private Integer idFactura;
     private Empresa empresa;
     private FormaPago formaPago;
     private UsuarioAcceso usuarioAccesoByIdUsuarioGeneradorFac;
     private UsuarioAcceso usuarioAccesoByIdUsuarioCliente;
     private String facNumero;
     private BigDecimal facSubtotal;
     private BigDecimal facTotalDescuento;
     private BigDecimal facPorcentajeIva;
     private BigDecimal facValorTotal;
     private Date facFechaEmision;
     private Date facFechaCaducidad;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public CabeceraFactura() {
    }

    public CabeceraFactura(Empresa empresa, FormaPago formaPago, UsuarioAcceso usuarioAccesoByIdUsuarioGeneradorFac, UsuarioAcceso usuarioAccesoByIdUsuarioCliente, String facNumero, BigDecimal facSubtotal, BigDecimal facTotalDescuento, BigDecimal facPorcentajeIva, BigDecimal facValorTotal, Date facFechaEmision, Date facFechaCaducidad, Set<DetalleFactura> detalleFacturas) {
       this.empresa = empresa;
       this.formaPago = formaPago;
       this.usuarioAccesoByIdUsuarioGeneradorFac = usuarioAccesoByIdUsuarioGeneradorFac;
       this.usuarioAccesoByIdUsuarioCliente = usuarioAccesoByIdUsuarioCliente;
       this.facNumero = facNumero;
       this.facSubtotal = facSubtotal;
       this.facTotalDescuento = facTotalDescuento;
       this.facPorcentajeIva = facPorcentajeIva;
       this.facValorTotal = facValorTotal;
       this.facFechaEmision = facFechaEmision;
       this.facFechaCaducidad = facFechaCaducidad;
       this.detalleFacturas = detalleFacturas;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }
    public UsuarioAcceso getUsuarioAccesoByIdUsuarioGeneradorFac() {
        return this.usuarioAccesoByIdUsuarioGeneradorFac;
    }
    
    public void setUsuarioAccesoByIdUsuarioGeneradorFac(UsuarioAcceso usuarioAccesoByIdUsuarioGeneradorFac) {
        this.usuarioAccesoByIdUsuarioGeneradorFac = usuarioAccesoByIdUsuarioGeneradorFac;
    }
    public UsuarioAcceso getUsuarioAccesoByIdUsuarioCliente() {
        return this.usuarioAccesoByIdUsuarioCliente;
    }
    
    public void setUsuarioAccesoByIdUsuarioCliente(UsuarioAcceso usuarioAccesoByIdUsuarioCliente) {
        this.usuarioAccesoByIdUsuarioCliente = usuarioAccesoByIdUsuarioCliente;
    }
    public String getFacNumero() {
        return this.facNumero;
    }
    
    public void setFacNumero(String facNumero) {
        this.facNumero = facNumero;
    }
    public BigDecimal getFacSubtotal() {
        return this.facSubtotal;
    }
    
    public void setFacSubtotal(BigDecimal facSubtotal) {
        this.facSubtotal = facSubtotal;
    }
    public BigDecimal getFacTotalDescuento() {
        return this.facTotalDescuento;
    }
    
    public void setFacTotalDescuento(BigDecimal facTotalDescuento) {
        this.facTotalDescuento = facTotalDescuento;
    }
    public BigDecimal getFacPorcentajeIva() {
        return this.facPorcentajeIva;
    }
    
    public void setFacPorcentajeIva(BigDecimal facPorcentajeIva) {
        this.facPorcentajeIva = facPorcentajeIva;
    }
    public BigDecimal getFacValorTotal() {
        return this.facValorTotal;
    }
    
    public void setFacValorTotal(BigDecimal facValorTotal) {
        this.facValorTotal = facValorTotal;
    }
    public Date getFacFechaEmision() {
        return this.facFechaEmision;
    }
    
    public void setFacFechaEmision(Date facFechaEmision) {
        this.facFechaEmision = facFechaEmision;
    }
    public Date getFacFechaCaducidad() {
        return this.facFechaCaducidad;
    }
    
    public void setFacFechaCaducidad(Date facFechaCaducidad) {
        this.facFechaCaducidad = facFechaCaducidad;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 89 * hash + Objects.hashCode(this.idFactura);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final CabeceraFactura other = (CabeceraFactura) obj;
        if (!Objects.equals(this.idFactura, other.idFactura)) {
            return false;
        }
        return true;
    }




}


