package ec.edu.saltos.modelo;
// Generated 21-ago-2020 20:56:19 by Hibernate Tools 4.3.1


import ec.edu.saltos.config.EstadosConfig;
import ec.edu.saltos.util.FechaUtil;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ConfigClave generated by hbm2java
 */
public class ConfigClave  implements java.io.Serializable {


     private int idConfigClave;
     private Integer claveCharMax;
     private Integer claveCharMin;
     private Boolean claveCharAlfanumerico;
     private Boolean claveCharMayus;
     private Boolean claveCharMinus;
     private Boolean claveCharEspecial;
     private String claveStrEspecial;
     private Integer claveCambiosDia;
     private Integer claveIntentosFallidos;
     private String claveUltimaClave;
     private Date claveFechaCreacion;
     private Date claveFechaMod;
     private Set<UsuarioAcceso> usuarioAccesos = new HashSet<UsuarioAcceso>(0);

    public ConfigClave() {
    }

	
    public ConfigClave(int idConfigClave) {
        this.idConfigClave = idConfigClave;
    }
    public ConfigClave(int idConfigClave, Integer claveCharMax, Integer claveCharMin, Boolean claveCharAlfanumerico, Boolean claveCharMayus, Boolean claveCharMinus, Boolean claveCharEspecial, String claveStrEspecial, Integer claveCambiosDia, Integer claveIntentosFallidos, String claveUltimaClave, Date claveFechaCreacion, Date claveFechaMod, Set<UsuarioAcceso> usuarioAccesos) {
       this.idConfigClave = idConfigClave;
       this.claveCharMax = claveCharMax;
       this.claveCharMin = claveCharMin;
       this.claveCharAlfanumerico = claveCharAlfanumerico;
       this.claveCharMayus = claveCharMayus;
       this.claveCharMinus = claveCharMinus;
       this.claveCharEspecial = claveCharEspecial;
       this.claveStrEspecial = claveStrEspecial;
       this.claveCambiosDia = claveCambiosDia;
       this.claveIntentosFallidos = claveIntentosFallidos;
       this.claveUltimaClave = claveUltimaClave;
       this.claveFechaCreacion = claveFechaCreacion;
       this.claveFechaMod = claveFechaMod;
       this.usuarioAccesos = usuarioAccesos;
    }
    
    public ConfigClave configClavePorDefecto(ConfigClave _config){
       _config.setClaveCharMax(EstadosConfig.CARACTERES_MAX_CLAVES.getId());
       _config.setClaveCharMin(EstadosConfig.CARACTERES_MIN_CLAVES.getId());
       _config.setClaveCharAlfanumerico((EstadosConfig.CARACTERES_ALFANUMERICOS.getId() == 1));
       _config.setClaveCharMayus((EstadosConfig.CARACTERES_MAX_CLAVES.getId() == 1));
       _config.setClaveCharMinus((EstadosConfig.CARACTERES_MAX_CLAVES.getId() == 1));
       _config.setClaveCharEspecial((EstadosConfig.CARACTERES_MAX_CLAVES.getId() == 1));
       _config.setClaveStrEspecial(EstadosConfig.CARACTERES_ESPECIALES_PERMITIDOS.getCodigo());
       _config.setClaveCambiosDia(EstadosConfig.NUMERO_CAMBIOS_POR_DIA.getId());
       _config.setClaveIntentosFallidos(EstadosConfig.INTENTOS_FALLIDOS.getId());
       _config.setClaveUltimaClave(EstadosConfig.ULTIMA_CLAVE.getCodigo());
       _config.setClaveFechaCreacion(FechaUtil.ahoraSinFormato());
       _config.setClaveFechaMod(FechaUtil.ahoraSinFormato());
       
        return _config;
    }
   
    public int getIdConfigClave() {
        return this.idConfigClave;
    }
    
    public void setIdConfigClave(int idConfigClave) {
        this.idConfigClave = idConfigClave;
    }
    public Integer getClaveCharMax() {
        return this.claveCharMax;
    }
    
    public void setClaveCharMax(Integer claveCharMax) {
        this.claveCharMax = claveCharMax;
    }
    public Integer getClaveCharMin() {
        return this.claveCharMin;
    }
    
    public void setClaveCharMin(Integer claveCharMin) {
        this.claveCharMin = claveCharMin;
    }
    public Boolean getClaveCharAlfanumerico() {
        return this.claveCharAlfanumerico;
    }
    
    public void setClaveCharAlfanumerico(Boolean claveCharAlfanumerico) {
        this.claveCharAlfanumerico = claveCharAlfanumerico;
    }
    public Boolean getClaveCharMayus() {
        return this.claveCharMayus;
    }
    
    public void setClaveCharMayus(Boolean claveCharMayus) {
        this.claveCharMayus = claveCharMayus;
    }
    public Boolean getClaveCharMinus() {
        return this.claveCharMinus;
    }
    
    public void setClaveCharMinus(Boolean claveCharMinus) {
        this.claveCharMinus = claveCharMinus;
    }
    public Boolean getClaveCharEspecial() {
        return this.claveCharEspecial;
    }
    
    public void setClaveCharEspecial(Boolean claveCharEspecial) {
        this.claveCharEspecial = claveCharEspecial;
    }
    public String getClaveStrEspecial() {
        return this.claveStrEspecial;
    }
    
    public void setClaveStrEspecial(String claveStrEspecial) {
        this.claveStrEspecial = claveStrEspecial;
    }
    public Integer getClaveCambiosDia() {
        return this.claveCambiosDia;
    }
    
    public void setClaveCambiosDia(Integer claveCambiosDia) {
        this.claveCambiosDia = claveCambiosDia;
    }
    public Integer getClaveIntentosFallidos() {
        return this.claveIntentosFallidos;
    }
    
    public void setClaveIntentosFallidos(Integer claveIntentosFallidos) {
        this.claveIntentosFallidos = claveIntentosFallidos;
    }
    public String getClaveUltimaClave() {
        return this.claveUltimaClave;
    }
    
    public void setClaveUltimaClave(String claveUltimaClave) {
        this.claveUltimaClave = claveUltimaClave;
    }
    public Date getClaveFechaCreacion() {
        return this.claveFechaCreacion;
    }
    
    public void setClaveFechaCreacion(Date claveFechaCreacion) {
        this.claveFechaCreacion = claveFechaCreacion;
    }
    public Date getClaveFechaMod() {
        return this.claveFechaMod;
    }
    
    public void setClaveFechaMod(Date claveFechaMod) {
        this.claveFechaMod = claveFechaMod;
    }
    public Set<UsuarioAcceso> getUsuarioAccesos() {
        return this.usuarioAccesos;
    }
    
    public void setUsuarioAccesos(Set<UsuarioAcceso> usuarioAccesos) {
        this.usuarioAccesos = usuarioAccesos;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 13 * hash + this.idConfigClave;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ConfigClave other = (ConfigClave) obj;
        if (this.idConfigClave != other.idConfigClave) {
            return false;
        }
        return true;
    }




}


