package ec.edu.saltos.modelo;
// Generated 31-ago-2020 17:42:00 by Hibernate Tools 4.3.1


import ec.edu.saltos.config.EstadosConfig;
import ec.edu.saltos.util.FechaUtil;
import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * ConfigClave generated by hbm2java
 */
public class ConfigClave  implements java.io.Serializable {


     private Integer idConfigClave;
     private Integer claveCharMax;
     private Integer claveCharMin;
     private Boolean claveCharAlfanumerico;
     private Boolean claveCharMayus;
     private Boolean claveCharMinus;
     private Boolean claveCharEspecial;
     private String claveStrEspecial;
     private Integer claveCambiosDia;
     private Integer claveIntentosFallidos;
     private String claveUltimaClave;
     private Date claveFechaCreacion;
     private Date claveFechaMod;
     private Set<UsuarioAcceso> usuarioAccesos = new HashSet<UsuarioAcceso>(0);

    public ConfigClave() {
    }

    public ConfigClave(Integer claveCharMax, Integer claveCharMin, Boolean claveCharAlfanumerico, Boolean claveCharMayus, Boolean claveCharMinus, Boolean claveCharEspecial, String claveStrEspecial, Integer claveCambiosDia, Integer claveIntentosFallidos, String claveUltimaClave, Date claveFechaCreacion, Date claveFechaMod, Set<UsuarioAcceso> usuarioAccesos) {
       this.claveCharMax = claveCharMax;
       this.claveCharMin = claveCharMin;
       this.claveCharAlfanumerico = claveCharAlfanumerico;
       this.claveCharMayus = claveCharMayus;
       this.claveCharMinus = claveCharMinus;
       this.claveCharEspecial = claveCharEspecial;
       this.claveStrEspecial = claveStrEspecial;
       this.claveCambiosDia = claveCambiosDia;
       this.claveIntentosFallidos = claveIntentosFallidos;
       this.claveUltimaClave = claveUltimaClave;
       this.claveFechaCreacion = claveFechaCreacion;
       this.claveFechaMod = claveFechaMod;
       this.usuarioAccesos = usuarioAccesos;
    }
    
    public ConfigClave(String _ultimaClave){
       this.claveCharMax = EstadosConfig.CARACTERES_MAX_CLAVES.getId();
       this.claveCharMin = EstadosConfig.CARACTERES_MIN_CLAVES.getId();
       this.claveCharAlfanumerico = (EstadosConfig.CARACTERES_ALFANUMERICOS.getId() == 1);
       this.claveCharMayus = (EstadosConfig.CARACTERES_MAX_CLAVES.getId() == 1);
       this.claveCharMinus = (EstadosConfig.CARACTERES_MAX_CLAVES.getId() == 1);
       this.claveCharEspecial = (EstadosConfig.CARACTERES_MAX_CLAVES.getId() == 1);
       this.claveStrEspecial = EstadosConfig.CARACTERES_ESPECIALES_PERMITIDOS.getCodigo();
       this.claveCambiosDia = EstadosConfig.NUMERO_CAMBIOS_POR_DIA.getId();
       this.claveIntentosFallidos = EstadosConfig.INTENTOS_FALLIDOS.getId();
       this.claveUltimaClave = _ultimaClave;
       this.claveFechaCreacion = FechaUtil.ahoraSinFormato();
       this.claveFechaMod = FechaUtil.ahoraSinFormato();
    }
   
    public Integer getIdConfigClave() {
        return this.idConfigClave;
    }
    
    public void setIdConfigClave(Integer idConfigClave) {
        this.idConfigClave = idConfigClave;
    }
    public Integer getClaveCharMax() {
        return this.claveCharMax;
    }
    
    public void setClaveCharMax(Integer claveCharMax) {
        this.claveCharMax = claveCharMax;
    }
    public Integer getClaveCharMin() {
        return this.claveCharMin;
    }
    
    public void setClaveCharMin(Integer claveCharMin) {
        this.claveCharMin = claveCharMin;
    }
    public Boolean getClaveCharAlfanumerico() {
        return this.claveCharAlfanumerico;
    }
    
    public void setClaveCharAlfanumerico(Boolean claveCharAlfanumerico) {
        this.claveCharAlfanumerico = claveCharAlfanumerico;
    }
    public Boolean getClaveCharMayus() {
        return this.claveCharMayus;
    }
    
    public void setClaveCharMayus(Boolean claveCharMayus) {
        this.claveCharMayus = claveCharMayus;
    }
    public Boolean getClaveCharMinus() {
        return this.claveCharMinus;
    }
    
    public void setClaveCharMinus(Boolean claveCharMinus) {
        this.claveCharMinus = claveCharMinus;
    }
    public Boolean getClaveCharEspecial() {
        return this.claveCharEspecial;
    }
    
    public void setClaveCharEspecial(Boolean claveCharEspecial) {
        this.claveCharEspecial = claveCharEspecial;
    }
    public String getClaveStrEspecial() {
        return this.claveStrEspecial;
    }
    
    public void setClaveStrEspecial(String claveStrEspecial) {
        this.claveStrEspecial = claveStrEspecial;
    }
    public Integer getClaveCambiosDia() {
        return this.claveCambiosDia;
    }
    
    public void setClaveCambiosDia(Integer claveCambiosDia) {
        this.claveCambiosDia = claveCambiosDia;
    }
    public Integer getClaveIntentosFallidos() {
        return this.claveIntentosFallidos;
    }
    
    public void setClaveIntentosFallidos(Integer claveIntentosFallidos) {
        this.claveIntentosFallidos = claveIntentosFallidos;
    }
    public String getClaveUltimaClave() {
        return this.claveUltimaClave;
    }
    
    public void setClaveUltimaClave(String claveUltimaClave) {
        this.claveUltimaClave = claveUltimaClave;
    }
    public Date getClaveFechaCreacion() {
        return this.claveFechaCreacion;
    }
    
    public void setClaveFechaCreacion(Date claveFechaCreacion) {
        this.claveFechaCreacion = claveFechaCreacion;
    }
    public Date getClaveFechaMod() {
        return this.claveFechaMod;
    }
    
    public void setClaveFechaMod(Date claveFechaMod) {
        this.claveFechaMod = claveFechaMod;
    }
    public Set<UsuarioAcceso> getUsuarioAccesos() {
        return this.usuarioAccesos;
    }
    
    public void setUsuarioAccesos(Set<UsuarioAcceso> usuarioAccesos) {
        this.usuarioAccesos = usuarioAccesos;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 89 * hash + Objects.hashCode(this.idConfigClave);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ConfigClave other = (ConfigClave) obj;
        if (!Objects.equals(this.idConfigClave, other.idConfigClave)) {
            return false;
        }
        return true;
    }




}


