package ec.edu.saltos.modelo;
// Generated 31-ago-2020 17:42:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CursosFormacion generated by hbm2java
 */
public class CursosFormacion  implements java.io.Serializable {


     private int idCurFormacion;
     private String nombreCurso;
     private String lugarCurso;
     private Date fechInicioCurso;
     private Date fechaFinCurso;
     private Set<FormacionParacaidista> formacionParacaidistas = new HashSet<FormacionParacaidista>(0);

    public CursosFormacion() {
    }

	
    public CursosFormacion(int idCurFormacion) {
        this.idCurFormacion = idCurFormacion;
    }
    public CursosFormacion(int idCurFormacion, String nombreCurso, String lugarCurso, Date fechInicioCurso, Date fechaFinCurso, Set<FormacionParacaidista> formacionParacaidistas) {
       this.idCurFormacion = idCurFormacion;
       this.nombreCurso = nombreCurso;
       this.lugarCurso = lugarCurso;
       this.fechInicioCurso = fechInicioCurso;
       this.fechaFinCurso = fechaFinCurso;
       this.formacionParacaidistas = formacionParacaidistas;
    }
   
    public int getIdCurFormacion() {
        return this.idCurFormacion;
    }
    
    public void setIdCurFormacion(int idCurFormacion) {
        this.idCurFormacion = idCurFormacion;
    }
    public String getNombreCurso() {
        return this.nombreCurso;
    }
    
    public void setNombreCurso(String nombreCurso) {
        this.nombreCurso = nombreCurso;
    }
    public String getLugarCurso() {
        return this.lugarCurso;
    }
    
    public void setLugarCurso(String lugarCurso) {
        this.lugarCurso = lugarCurso;
    }
    public Date getFechInicioCurso() {
        return this.fechInicioCurso;
    }
    
    public void setFechInicioCurso(Date fechInicioCurso) {
        this.fechInicioCurso = fechInicioCurso;
    }
    public Date getFechaFinCurso() {
        return this.fechaFinCurso;
    }
    
    public void setFechaFinCurso(Date fechaFinCurso) {
        this.fechaFinCurso = fechaFinCurso;
    }
    public Set<FormacionParacaidista> getFormacionParacaidistas() {
        return this.formacionParacaidistas;
    }
    
    public void setFormacionParacaidistas(Set<FormacionParacaidista> formacionParacaidistas) {
        this.formacionParacaidistas = formacionParacaidistas;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + this.idCurFormacion;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final CursosFormacion other = (CursosFormacion) obj;
        if (this.idCurFormacion != other.idCurFormacion) {
            return false;
        }
        return true;
    }




}


