package ec.edu.saltos.modelo;
// Generated 31-ago-2020 17:42:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int idEmpresa;
     private String empRazonSocial;
     private String empRuc;
     private String empDireccion;
     private String empTelefono;
     private String empCorreo;
     private Integer numResoContribuyenteSri;
     private String numAutorizacionSri;
     private Boolean obligadoLlevarContabilidad;
     private Date empFechaCreacion;
     private Date empFechaMod;
     private Set<CabeceraFactura> cabeceraFacturas = new HashSet<CabeceraFactura>(0);

    public Empresa() {
    }

	
    public Empresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Empresa(int idEmpresa, String empRazonSocial, String empRuc, String empDireccion, String empTelefono, String empCorreo, Integer numResoContribuyenteSri, String numAutorizacionSri, Boolean obligadoLlevarContabilidad, Date empFechaCreacion, Date empFechaMod, Set<CabeceraFactura> cabeceraFacturas) {
       this.idEmpresa = idEmpresa;
       this.empRazonSocial = empRazonSocial;
       this.empRuc = empRuc;
       this.empDireccion = empDireccion;
       this.empTelefono = empTelefono;
       this.empCorreo = empCorreo;
       this.numResoContribuyenteSri = numResoContribuyenteSri;
       this.numAutorizacionSri = numAutorizacionSri;
       this.obligadoLlevarContabilidad = obligadoLlevarContabilidad;
       this.empFechaCreacion = empFechaCreacion;
       this.empFechaMod = empFechaMod;
       this.cabeceraFacturas = cabeceraFacturas;
    }
   
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getEmpRazonSocial() {
        return this.empRazonSocial;
    }
    
    public void setEmpRazonSocial(String empRazonSocial) {
        this.empRazonSocial = empRazonSocial;
    }
    public String getEmpRuc() {
        return this.empRuc;
    }
    
    public void setEmpRuc(String empRuc) {
        this.empRuc = empRuc;
    }
    public String getEmpDireccion() {
        return this.empDireccion;
    }
    
    public void setEmpDireccion(String empDireccion) {
        this.empDireccion = empDireccion;
    }
    public String getEmpTelefono() {
        return this.empTelefono;
    }
    
    public void setEmpTelefono(String empTelefono) {
        this.empTelefono = empTelefono;
    }
    public String getEmpCorreo() {
        return this.empCorreo;
    }
    
    public void setEmpCorreo(String empCorreo) {
        this.empCorreo = empCorreo;
    }
    public Integer getNumResoContribuyenteSri() {
        return this.numResoContribuyenteSri;
    }
    
    public void setNumResoContribuyenteSri(Integer numResoContribuyenteSri) {
        this.numResoContribuyenteSri = numResoContribuyenteSri;
    }
    public String getNumAutorizacionSri() {
        return this.numAutorizacionSri;
    }
    
    public void setNumAutorizacionSri(String numAutorizacionSri) {
        this.numAutorizacionSri = numAutorizacionSri;
    }
    public Boolean getObligadoLlevarContabilidad() {
        return this.obligadoLlevarContabilidad;
    }
    
    public void setObligadoLlevarContabilidad(Boolean obligadoLlevarContabilidad) {
        this.obligadoLlevarContabilidad = obligadoLlevarContabilidad;
    }
    public Date getEmpFechaCreacion() {
        return this.empFechaCreacion;
    }
    
    public void setEmpFechaCreacion(Date empFechaCreacion) {
        this.empFechaCreacion = empFechaCreacion;
    }
    public Date getEmpFechaMod() {
        return this.empFechaMod;
    }
    
    public void setEmpFechaMod(Date empFechaMod) {
        this.empFechaMod = empFechaMod;
    }
    public Set<CabeceraFactura> getCabeceraFacturas() {
        return this.cabeceraFacturas;
    }
    
    public void setCabeceraFacturas(Set<CabeceraFactura> cabeceraFacturas) {
        this.cabeceraFacturas = cabeceraFacturas;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 29 * hash + this.idEmpresa;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Empresa other = (Empresa) obj;
        if (this.idEmpresa != other.idEmpresa) {
            return false;
        }
        return true;
    }




}


