package ec.edu.saltos.modelo;
// Generated 31-ago-2020 17:42:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Objects;

/**
 * FormacionParacaidista generated by hbm2java
 */
public class FormacionParacaidista  implements java.io.Serializable {


     private Integer idForParacaidista;
     private CursosFormacion cursosFormacion;
     private Paracaidista paracaidista;
     private Date forParFechaCreacion;

    public FormacionParacaidista() {
    }

    public FormacionParacaidista(CursosFormacion cursosFormacion, Paracaidista paracaidista, Date forParFechaCreacion) {
       this.cursosFormacion = cursosFormacion;
       this.paracaidista = paracaidista;
       this.forParFechaCreacion = forParFechaCreacion;
    }
   
    public Integer getIdForParacaidista() {
        return this.idForParacaidista;
    }
    
    public void setIdForParacaidista(Integer idForParacaidista) {
        this.idForParacaidista = idForParacaidista;
    }
    public CursosFormacion getCursosFormacion() {
        return this.cursosFormacion;
    }
    
    public void setCursosFormacion(CursosFormacion cursosFormacion) {
        this.cursosFormacion = cursosFormacion;
    }
    public Paracaidista getParacaidista() {
        return this.paracaidista;
    }
    
    public void setParacaidista(Paracaidista paracaidista) {
        this.paracaidista = paracaidista;
    }
    public Date getForParFechaCreacion() {
        return this.forParFechaCreacion;
    }
    
    public void setForParFechaCreacion(Date forParFechaCreacion) {
        this.forParFechaCreacion = forParFechaCreacion;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 83 * hash + Objects.hashCode(this.idForParacaidista);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FormacionParacaidista other = (FormacionParacaidista) obj;
        if (!Objects.equals(this.idForParacaidista, other.idForParacaidista)) {
            return false;
        }
        return true;
    }




}


