package ec.edu.saltos.modelo;
// Generated 31-ago-2020 17:42:00 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * OpcionPerfil generated by hbm2java
 */
public class OpcionPerfil  implements java.io.Serializable {


     private Integer idPermiso;
     private Opcion opcion;
     private Perfil perfil;
     private String opcPerEstatus;

    public OpcionPerfil() {
    }

    public OpcionPerfil(Opcion opcion, Perfil perfil, String opcPerEstatus) {
       this.opcion = opcion;
       this.perfil = perfil;
       this.opcPerEstatus = opcPerEstatus;
    }
   
    public Integer getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(Integer idPermiso) {
        this.idPermiso = idPermiso;
    }
    public Opcion getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(Opcion opcion) {
        this.opcion = opcion;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getOpcPerEstatus() {
        return this.opcPerEstatus;
    }
    
    public void setOpcPerEstatus(String opcPerEstatus) {
        this.opcPerEstatus = opcPerEstatus;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 61 * hash + Objects.hashCode(this.idPermiso);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final OpcionPerfil other = (OpcionPerfil) obj;
        if (!Objects.equals(this.idPermiso, other.idPermiso)) {
            return false;
        }
        return true;
    }




}


