package ec.edu.saltos.modelo;
// Generated 31-ago-2020 17:42:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Paracaidista generated by hbm2java
 */
public class Paracaidista  implements java.io.Serializable {


     private Integer idParacaidista;
     private UsuarioAcceso usuarioAcceso;
     private String tipoParacaidista;
     private String escuelaFormacion;
     private Integer numSaltosCompletados;
     private Date fechaUltimoSalto;
     private Boolean licencia;
     private Date fechaCaducidadLicencia;
     private Set<FormacionParacaidista> formacionParacaidistas = new HashSet<FormacionParacaidista>(0);
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Paracaidista() {
    }

    public Paracaidista(UsuarioAcceso usuarioAcceso, String tipoParacaidista, String escuelaFormacion, Integer numSaltosCompletados, Date fechaUltimoSalto, Boolean licencia, Date fechaCaducidadLicencia, Set<FormacionParacaidista> formacionParacaidistas, Set<Pedido> pedidos) {
       this.usuarioAcceso = usuarioAcceso;
       this.tipoParacaidista = tipoParacaidista;
       this.escuelaFormacion = escuelaFormacion;
       this.numSaltosCompletados = numSaltosCompletados;
       this.fechaUltimoSalto = fechaUltimoSalto;
       this.licencia = licencia;
       this.fechaCaducidadLicencia = fechaCaducidadLicencia;
       this.formacionParacaidistas = formacionParacaidistas;
       this.pedidos = pedidos;
    }
   
    public Integer getIdParacaidista() {
        return this.idParacaidista;
    }
    
    public void setIdParacaidista(Integer idParacaidista) {
        this.idParacaidista = idParacaidista;
    }
    public UsuarioAcceso getUsuarioAcceso() {
        return this.usuarioAcceso;
    }
    
    public void setUsuarioAcceso(UsuarioAcceso usuarioAcceso) {
        this.usuarioAcceso = usuarioAcceso;
    }
    public String getTipoParacaidista() {
        return this.tipoParacaidista;
    }
    
    public void setTipoParacaidista(String tipoParacaidista) {
        this.tipoParacaidista = tipoParacaidista;
    }
    public String getEscuelaFormacion() {
        return this.escuelaFormacion;
    }
    
    public void setEscuelaFormacion(String escuelaFormacion) {
        this.escuelaFormacion = escuelaFormacion;
    }
    public Integer getNumSaltosCompletados() {
        return this.numSaltosCompletados;
    }
    
    public void setNumSaltosCompletados(Integer numSaltosCompletados) {
        this.numSaltosCompletados = numSaltosCompletados;
    }
    public Date getFechaUltimoSalto() {
        return this.fechaUltimoSalto;
    }
    
    public void setFechaUltimoSalto(Date fechaUltimoSalto) {
        this.fechaUltimoSalto = fechaUltimoSalto;
    }
    public Boolean getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(Boolean licencia) {
        this.licencia = licencia;
    }
    public Date getFechaCaducidadLicencia() {
        return this.fechaCaducidadLicencia;
    }
    
    public void setFechaCaducidadLicencia(Date fechaCaducidadLicencia) {
        this.fechaCaducidadLicencia = fechaCaducidadLicencia;
    }
    public Set<FormacionParacaidista> getFormacionParacaidistas() {
        return this.formacionParacaidistas;
    }
    
    public void setFormacionParacaidistas(Set<FormacionParacaidista> formacionParacaidistas) {
        this.formacionParacaidistas = formacionParacaidistas;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 23 * hash + Objects.hashCode(this.idParacaidista);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Paracaidista other = (Paracaidista) obj;
        if (!Objects.equals(this.idParacaidista, other.idParacaidista)) {
            return false;
        }
        return true;
    }




}


