package ec.edu.saltos.modelo;
// Generated 31-ago-2020 17:42:00 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer idPedido;
     private Descuento descuento;
     private Paracaidista paracaidista;
     private Salto salto;
     private ServicioAdicional servicioAdicional;
     private Vuelo vuelo;
     private BigDecimal costoSalto;
     private BigDecimal costoTotalPedido;
     private Date fecaARealizarseSalto;
     private Boolean estatusFacturacion;
     private Date fechaPedido;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Pedido() {
    }

    public Pedido(Descuento descuento, Paracaidista paracaidista, Salto salto, ServicioAdicional servicioAdicional, Vuelo vuelo, BigDecimal costoSalto, BigDecimal costoTotalPedido, Date fecaARealizarseSalto, Boolean estatusFacturacion, Date fechaPedido, Set<DetalleFactura> detalleFacturas) {
       this.descuento = descuento;
       this.paracaidista = paracaidista;
       this.salto = salto;
       this.servicioAdicional = servicioAdicional;
       this.vuelo = vuelo;
       this.costoSalto = costoSalto;
       this.costoTotalPedido = costoTotalPedido;
       this.fecaARealizarseSalto = fecaARealizarseSalto;
       this.estatusFacturacion = estatusFacturacion;
       this.fechaPedido = fechaPedido;
       this.detalleFacturas = detalleFacturas;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Descuento getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Descuento descuento) {
        this.descuento = descuento;
    }
    public Paracaidista getParacaidista() {
        return this.paracaidista;
    }
    
    public void setParacaidista(Paracaidista paracaidista) {
        this.paracaidista = paracaidista;
    }
    public Salto getSalto() {
        return this.salto;
    }
    
    public void setSalto(Salto salto) {
        this.salto = salto;
    }
    public ServicioAdicional getServicioAdicional() {
        return this.servicioAdicional;
    }
    
    public void setServicioAdicional(ServicioAdicional servicioAdicional) {
        this.servicioAdicional = servicioAdicional;
    }
    public Vuelo getVuelo() {
        return this.vuelo;
    }
    
    public void setVuelo(Vuelo vuelo) {
        this.vuelo = vuelo;
    }
    public BigDecimal getCostoSalto() {
        return this.costoSalto;
    }
    
    public void setCostoSalto(BigDecimal costoSalto) {
        this.costoSalto = costoSalto;
    }
    public BigDecimal getCostoTotalPedido() {
        return this.costoTotalPedido;
    }
    
    public void setCostoTotalPedido(BigDecimal costoTotalPedido) {
        this.costoTotalPedido = costoTotalPedido;
    }
    public Date getFecaARealizarseSalto() {
        return this.fecaARealizarseSalto;
    }
    
    public void setFecaARealizarseSalto(Date fecaARealizarseSalto) {
        this.fecaARealizarseSalto = fecaARealizarseSalto;
    }
    public Boolean getEstatusFacturacion() {
        return this.estatusFacturacion;
    }
    
    public void setEstatusFacturacion(Boolean estatusFacturacion) {
        this.estatusFacturacion = estatusFacturacion;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 29 * hash + Objects.hashCode(this.idPedido);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Pedido other = (Pedido) obj;
        if (!Objects.equals(this.idPedido, other.idPedido)) {
            return false;
        }
        return true;
    }




}


