package ec.edu.saltos.modelo;
// Generated 21-ago-2020 20:56:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private int idPerfil;
     private String perfilNombre;
     private String perfilDescripcion;
     private String perfilEstatus;
     private String perfilEstatus2;
     private Set<AsignarPerfil> asignarPerfils = new HashSet<AsignarPerfil>(0);
     private Set<OpcionPerfil> opcionPerfils = new HashSet<OpcionPerfil>(0);

    public Perfil() {
    }

	
    public Perfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public Perfil(int idPerfil, String perfilNombre, String perfilDescripcion, String perfilEstatus, String perfilEstatus2, Set<AsignarPerfil> asignarPerfils, Set<OpcionPerfil> opcionPerfils) {
       this.idPerfil = idPerfil;
       this.perfilNombre = perfilNombre;
       this.perfilDescripcion = perfilDescripcion;
       this.perfilEstatus = perfilEstatus;
       this.perfilEstatus2 = perfilEstatus2;
       this.asignarPerfils = asignarPerfils;
       this.opcionPerfils = opcionPerfils;
    }
   
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public String getPerfilNombre() {
        return this.perfilNombre;
    }
    
    public void setPerfilNombre(String perfilNombre) {
        this.perfilNombre = perfilNombre;
    }
    public String getPerfilDescripcion() {
        return this.perfilDescripcion;
    }
    
    public void setPerfilDescripcion(String perfilDescripcion) {
        this.perfilDescripcion = perfilDescripcion;
    }
    public String getPerfilEstatus() {
        return this.perfilEstatus;
    }
    
    public void setPerfilEstatus(String perfilEstatus) {
        this.perfilEstatus = perfilEstatus;
    }
    public String getPerfilEstatus2() {
        return this.perfilEstatus2;
    }
    
    public void setPerfilEstatus2(String perfilEstatus2) {
        this.perfilEstatus2 = perfilEstatus2;
    }
    public Set<AsignarPerfil> getAsignarPerfils() {
        return this.asignarPerfils;
    }
    
    public void setAsignarPerfils(Set<AsignarPerfil> asignarPerfils) {
        this.asignarPerfils = asignarPerfils;
    }
    public Set<OpcionPerfil> getOpcionPerfils() {
        return this.opcionPerfils;
    }
    
    public void setOpcionPerfils(Set<OpcionPerfil> opcionPerfils) {
        this.opcionPerfils = opcionPerfils;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 71 * hash + this.idPerfil;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Perfil other = (Perfil) obj;
        if (this.idPerfil != other.idPerfil) {
            return false;
        }
        return true;
    }

}


