package ec.edu.saltos.modelo;
// Generated 21-ago-2020 20:56:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idPersona;
     private String perNombres;
     private String perApellidos;
     private String perDireccion;
     private String perIdentificacion;
     private Date perFechaNacimiento;
     private String perTelefono;
     private String perCorreo;
     private String perFoto;
     private Date perFechaCreacion;
     private Date perFechaMod;
     private String perEstatus;
     private Set<UsuarioAcceso> usuarioAccesos = new HashSet<UsuarioAcceso>(0);

    public Persona() {
    }

	
    public Persona(int idPersona) {
        this.idPersona = idPersona;
    }
    public Persona(int idPersona, String perNombres, String perApellidos, String perDireccion, String perIdentificacion, Date perFechaNacimiento, String perTelefono, String perCorreo, String perFoto, Date perFechaCreacion, Date perFechaMod, String perEstatus, Set<UsuarioAcceso> usuarioAccesos) {
       this.idPersona = idPersona;
       this.perNombres = perNombres;
       this.perApellidos = perApellidos;
       this.perDireccion = perDireccion;
       this.perIdentificacion = perIdentificacion;
       this.perFechaNacimiento = perFechaNacimiento;
       this.perTelefono = perTelefono;
       this.perCorreo = perCorreo;
       this.perFoto = perFoto;
       this.perFechaCreacion = perFechaCreacion;
       this.perFechaMod = perFechaMod;
       this.perEstatus = perEstatus;
       this.usuarioAccesos = usuarioAccesos;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public String getPerNombres() {
        return this.perNombres;
    }
    
    public void setPerNombres(String perNombres) {
        this.perNombres = perNombres;
    }
    public String getPerApellidos() {
        return this.perApellidos;
    }
    
    public void setPerApellidos(String perApellidos) {
        this.perApellidos = perApellidos;
    }
    public String getPerDireccion() {
        return this.perDireccion;
    }
    
    public void setPerDireccion(String perDireccion) {
        this.perDireccion = perDireccion;
    }
    public String getPerIdentificacion() {
        return this.perIdentificacion;
    }
    
    public void setPerIdentificacion(String perIdentificacion) {
        this.perIdentificacion = perIdentificacion;
    }
    public Date getPerFechaNacimiento() {
        return this.perFechaNacimiento;
    }
    
    public void setPerFechaNacimiento(Date perFechaNacimiento) {
        this.perFechaNacimiento = perFechaNacimiento;
    }
    public String getPerTelefono() {
        return this.perTelefono;
    }
    
    public void setPerTelefono(String perTelefono) {
        this.perTelefono = perTelefono;
    }
    public String getPerCorreo() {
        return this.perCorreo;
    }
    
    public void setPerCorreo(String perCorreo) {
        this.perCorreo = perCorreo;
    }
    public String getPerFoto() {
        return this.perFoto;
    }
    
    public void setPerFoto(String perFoto) {
        this.perFoto = perFoto;
    }
    public Date getPerFechaCreacion() {
        return this.perFechaCreacion;
    }
    
    public void setPerFechaCreacion(Date perFechaCreacion) {
        this.perFechaCreacion = perFechaCreacion;
    }
    public Date getPerFechaMod() {
        return this.perFechaMod;
    }
    
    public void setPerFechaMod(Date perFechaMod) {
        this.perFechaMod = perFechaMod;
    }
    public String getPerEstatus() {
        return this.perEstatus;
    }
    
    public void setPerEstatus(String perEstatus) {
        this.perEstatus = perEstatus;
    }
    public Set<UsuarioAcceso> getUsuarioAccesos() {
        return this.usuarioAccesos;
    }
    
    public void setUsuarioAccesos(Set<UsuarioAcceso> usuarioAccesos) {
        this.usuarioAccesos = usuarioAccesos;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 83 * hash + this.idPersona;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Persona other = (Persona) obj;
        if (this.idPersona != other.idPersona) {
            return false;
        }
        return true;
    }




}


