package ec.edu.saltos.modelo;
// Generated 31-ago-2020 17:42:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Salto generated by hbm2java
 */
public class Salto  implements java.io.Serializable {


     private int idSalto;
     private String tipoSalto;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Salto() {
    }

	
    public Salto(int idSalto) {
        this.idSalto = idSalto;
    }
    public Salto(int idSalto, String tipoSalto, Set<Pedido> pedidos) {
       this.idSalto = idSalto;
       this.tipoSalto = tipoSalto;
       this.pedidos = pedidos;
    }
   
    public int getIdSalto() {
        return this.idSalto;
    }
    
    public void setIdSalto(int idSalto) {
        this.idSalto = idSalto;
    }
    public String getTipoSalto() {
        return this.tipoSalto;
    }
    
    public void setTipoSalto(String tipoSalto) {
        this.tipoSalto = tipoSalto;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + this.idSalto;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Salto other = (Salto) obj;
        if (this.idSalto != other.idSalto) {
            return false;
        }
        return true;
    }




}


