package ec.edu.saltos.modelo;
// Generated 31-ago-2020 17:42:00 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * ServicioAdicional generated by hbm2java
 */
public class ServicioAdicional  implements java.io.Serializable {


     private Integer idServicioAdicional;
     private UsuarioAcceso usuarioAcceso;
     private String serNombre;
     private String serDescripcion;
     private BigDecimal serCosto;
     private Date serFechaCreacion;
     private Date serFechaMod;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public ServicioAdicional() {
    }

    public ServicioAdicional(UsuarioAcceso usuarioAcceso, String serNombre, String serDescripcion, BigDecimal serCosto, Date serFechaCreacion, Date serFechaMod, Set<Pedido> pedidos) {
       this.usuarioAcceso = usuarioAcceso;
       this.serNombre = serNombre;
       this.serDescripcion = serDescripcion;
       this.serCosto = serCosto;
       this.serFechaCreacion = serFechaCreacion;
       this.serFechaMod = serFechaMod;
       this.pedidos = pedidos;
    }
   
    public Integer getIdServicioAdicional() {
        return this.idServicioAdicional;
    }
    
    public void setIdServicioAdicional(Integer idServicioAdicional) {
        this.idServicioAdicional = idServicioAdicional;
    }
    public UsuarioAcceso getUsuarioAcceso() {
        return this.usuarioAcceso;
    }
    
    public void setUsuarioAcceso(UsuarioAcceso usuarioAcceso) {
        this.usuarioAcceso = usuarioAcceso;
    }
    public String getSerNombre() {
        return this.serNombre;
    }
    
    public void setSerNombre(String serNombre) {
        this.serNombre = serNombre;
    }
    public String getSerDescripcion() {
        return this.serDescripcion;
    }
    
    public void setSerDescripcion(String serDescripcion) {
        this.serDescripcion = serDescripcion;
    }
    public BigDecimal getSerCosto() {
        return this.serCosto;
    }
    
    public void setSerCosto(BigDecimal serCosto) {
        this.serCosto = serCosto;
    }
    public Date getSerFechaCreacion() {
        return this.serFechaCreacion;
    }
    
    public void setSerFechaCreacion(Date serFechaCreacion) {
        this.serFechaCreacion = serFechaCreacion;
    }
    public Date getSerFechaMod() {
        return this.serFechaMod;
    }
    
    public void setSerFechaMod(Date serFechaMod) {
        this.serFechaMod = serFechaMod;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.idServicioAdicional);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ServicioAdicional other = (ServicioAdicional) obj;
        if (!Objects.equals(this.idServicioAdicional, other.idServicioAdicional)) {
            return false;
        }
        return true;
    }




}


