package ec.edu.saltos.modelo;
// Generated 21-ago-2020 20:56:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * UsuarioAcceso generated by hbm2java
 */
public class UsuarioAcceso  implements java.io.Serializable {


     private Integer idUsuarioAcceso;
     private ConfigClave configClave;
     private Persona persona;
     private String usrAccesoNombre;
     private String usrAccesoClave;
     private Integer usrAccesoIntentosFallidos;
     private String usrAccesoEstatus;
     private Date usrAccesoFechaCreacion;
     private Date usrAccesoFechaMod;
     private Set<AsignarPerfil> asignarPerfils = new HashSet<AsignarPerfil>(0);
     private Set<Bitacora> bitacoras = new HashSet<Bitacora>(0);

    public UsuarioAcceso() {
    }

    public UsuarioAcceso(ConfigClave configClave, Persona persona, String usrAccesoNombre, String usrAccesoClave, Integer usrAccesoIntentosFallidos, String usrAccesoEstatus, Date usrAccesoFechaCreacion, Date usrAccesoFechaMod, Set<AsignarPerfil> asignarPerfils, Set<Bitacora> bitacoras) {
       this.configClave = configClave;
       this.persona = persona;
       this.usrAccesoNombre = usrAccesoNombre;
       this.usrAccesoClave = usrAccesoClave;
       this.usrAccesoIntentosFallidos = usrAccesoIntentosFallidos;
       this.usrAccesoEstatus = usrAccesoEstatus;
       this.usrAccesoFechaCreacion = usrAccesoFechaCreacion;
       this.usrAccesoFechaMod = usrAccesoFechaMod;
       this.asignarPerfils = asignarPerfils;
       this.bitacoras = bitacoras;
    }
   
    public Integer getIdUsuarioAcceso() {
        return this.idUsuarioAcceso;
    }
    
    public void setIdUsuarioAcceso(Integer idUsuarioAcceso) {
        this.idUsuarioAcceso = idUsuarioAcceso;
    }
    public ConfigClave getConfigClave() {
        return this.configClave;
    }
    
    public void setConfigClave(ConfigClave configClave) {
        this.configClave = configClave;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getUsrAccesoNombre() {
        return this.usrAccesoNombre;
    }
    
    public void setUsrAccesoNombre(String usrAccesoNombre) {
        this.usrAccesoNombre = usrAccesoNombre;
    }
    public String getUsrAccesoClave() {
        return this.usrAccesoClave;
    }
    
    public void setUsrAccesoClave(String usrAccesoClave) {
        this.usrAccesoClave = usrAccesoClave;
    }
    public Integer getUsrAccesoIntentosFallidos() {
        return this.usrAccesoIntentosFallidos;
    }
    
    public void setUsrAccesoIntentosFallidos(Integer usrAccesoIntentosFallidos) {
        this.usrAccesoIntentosFallidos = usrAccesoIntentosFallidos;
    }
    public String getUsrAccesoEstatus() {
        return this.usrAccesoEstatus;
    }
    
    public void setUsrAccesoEstatus(String usrAccesoEstatus) {
        this.usrAccesoEstatus = usrAccesoEstatus;
    }
    public Date getUsrAccesoFechaCreacion() {
        return this.usrAccesoFechaCreacion;
    }
    
    public void setUsrAccesoFechaCreacion(Date usrAccesoFechaCreacion) {
        this.usrAccesoFechaCreacion = usrAccesoFechaCreacion;
    }
    public Date getUsrAccesoFechaMod() {
        return this.usrAccesoFechaMod;
    }
    
    public void setUsrAccesoFechaMod(Date usrAccesoFechaMod) {
        this.usrAccesoFechaMod = usrAccesoFechaMod;
    }
    public Set<AsignarPerfil> getAsignarPerfils() {
        return this.asignarPerfils;
    }
    
    public void setAsignarPerfils(Set<AsignarPerfil> asignarPerfils) {
        this.asignarPerfils = asignarPerfils;
    }
    public Set<Bitacora> getBitacoras() {
        return this.bitacoras;
    }
    
    public void setBitacoras(Set<Bitacora> bitacoras) {
        this.bitacoras = bitacoras;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.idUsuarioAcceso);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final UsuarioAcceso other = (UsuarioAcceso) obj;
        if (!Objects.equals(this.idUsuarioAcceso, other.idUsuarioAcceso)) {
            return false;
        }
        return true;
    }




}


