package ec.edu.saltos.modelo;
// Generated 31-ago-2020 17:42:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Vuelo generated by hbm2java
 */
public class Vuelo  implements java.io.Serializable {


     private Integer idVuelo;
     private Aeronave aeronave;
     private UsuarioAcceso usuarioAcceso;
     private Date vueHoraSalida;
     private Date vueHoraLlegada;
     private Integer vuePersonasABordo;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Vuelo() {
    }

    public Vuelo(Aeronave aeronave, UsuarioAcceso usuarioAcceso, Date vueHoraSalida, Date vueHoraLlegada, Integer vuePersonasABordo, Set<Pedido> pedidos) {
       this.aeronave = aeronave;
       this.usuarioAcceso = usuarioAcceso;
       this.vueHoraSalida = vueHoraSalida;
       this.vueHoraLlegada = vueHoraLlegada;
       this.vuePersonasABordo = vuePersonasABordo;
       this.pedidos = pedidos;
    }
   
    public Integer getIdVuelo() {
        return this.idVuelo;
    }
    
    public void setIdVuelo(Integer idVuelo) {
        this.idVuelo = idVuelo;
    }
    public Aeronave getAeronave() {
        return this.aeronave;
    }
    
    public void setAeronave(Aeronave aeronave) {
        this.aeronave = aeronave;
    }
    public UsuarioAcceso getUsuarioAcceso() {
        return this.usuarioAcceso;
    }
    
    public void setUsuarioAcceso(UsuarioAcceso usuarioAcceso) {
        this.usuarioAcceso = usuarioAcceso;
    }
    public Date getVueHoraSalida() {
        return this.vueHoraSalida;
    }
    
    public void setVueHoraSalida(Date vueHoraSalida) {
        this.vueHoraSalida = vueHoraSalida;
    }
    public Date getVueHoraLlegada() {
        return this.vueHoraLlegada;
    }
    
    public void setVueHoraLlegada(Date vueHoraLlegada) {
        this.vueHoraLlegada = vueHoraLlegada;
    }
    public Integer getVuePersonasABordo() {
        return this.vuePersonasABordo;
    }
    
    public void setVuePersonasABordo(Integer vuePersonasABordo) {
        this.vuePersonasABordo = vuePersonasABordo;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 71 * hash + Objects.hashCode(this.idVuelo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Vuelo other = (Vuelo) obj;
        if (!Objects.equals(this.idVuelo, other.idVuelo)) {
            return false;
        }
        return true;
    }




}


