package ec.edu.saltos.config;

/**
 *
 * @author guffenix
 */
public enum EstadosConfig {
    
    //    AMBIENTES
    AMBIENTE("DESARROLLO - SISTEMA DE SALTOS", "dev", 0),

    //    ESTATUS
    ACTIVADO("ACTIVADO","ACT",0),
    DESACTIVADO("DESACTIVADO","DES",0),
    //    PERFIL
    PERFIL_ESTADO_ACTIVO("PERFIL ACTIVO", "PAC", 0),
    PERFIL_ESTADO_DESACTIVADO("PERFIL DESACTIVADO", "PDE", 0),
    PERFIL_ADMINISTRADOR("PERFIL DE ADMINISTRADOR ", "ADM", 0),
    PERFIL_USUARIO("PERFIL DE USUARIO", "USR", 0),
    PERFIL_INVITADO("PERFIL DE INVITADO", "INV", 0),
    //    PERMISO
    PERMISO_ACTIVO("PERMISO ACTIVO", "ACT", 0),
    PERMISO_INACTIVO("PERMISO INACTIVO", "INA", 0),

    //    RECURSO
    RECURSO_OCULTO("OCULTO", "OCU", 0),
    RECURSO_CATEGORIA("IDENTIFICACION CATEGORIA", "0", 0),
    RECURSO_PLANTILLA("IDENTIFIICACION PLANTILLA", "1", 0),
    RECURSO_ORIGEN("RECURSO ORIGEN", "Origen", 0),
    //    CLAVE
    CLAVE_USUARIO("CLAVE TIPO USUARIO", "USR", 0),
    CLAVE_REENVIADA("CLAVE TIPO REENVIO", "CAM", 0),
    CLAVE_CADUCADA("CLAVE CADUCADA", "CCA", 0),
    CLAVE_ERRONEA("CLAVE ERRONEA", "ERR", 0),
    CLAVE_ACTIVA("CLAVE ACTIVO", "ACT", 0),
    //    CORREO
    HOST_CORREO_NOTIFICACION("HOST_CORREO_NOTIFICACION", "", 0),
    PUERTO_CORREO_NOTIFICACION("PUERTO_CORREO_NOTIFICACION", "587", 0),
    USUARIO_CORREO_NOTIFICACION("USUARIO_CORREO_NOTIFICACION", "kataday@espe.edu.ec", 0),
    CLAVE_CORREO_NOTIFICACION("PASSWORD_CORREO_NOTIFICACION", "", 0),
    CUENTA_CORREO_NOTIFICACION("CUENTA_CORREO_NOTIFICACION", "", 0),
    CUENTA_DESACTIVADA("CUENTA DESACTIVADA", "CDE", 0),
    MODO_NOTIFICACION_CORREO("CUENTA CORREO", "1", 0),
    //    PREFERENCIAS APP
    APP_TEMA_USER("TEMA AZUL OSCURO", "azul-claro", 0),
    APP_LAYOUT_USER("CAPAS AZUL OSCURO, BOTONES, ETC", "rojo", 0),
    APP_CONSTRUCCION("RECURSO EN CONSTRUCCION", "/usr/pagina-construccion", 0),
    //    EMPRESA
    NOMBRE_EMPRESA("LOS GARRAPATEROS","LOS GARRAPATEROS",0),
    HORA_INICIO_ATENCION("10:00 A.M.","10:00:00",0),
    DIAS_ATENCION("FIN DE SEMANA","VIERNES,SABADO,DOMINGO",0),
    DESCUENTO__LIBRE_2T_1P("2 TANDEM - 1 SALTO LIBRE","",40),
    DESCUENTO__LIBRE_1T_3P("1 TANDEM - 3 SALTOS LIBRES","",50),
    DESCUENTO__LIBRE_5P("5 SALTOS LIBRES","",60),
    //Versionamiento
    VERSION_APP("Versión del Aplicativo", "1.0.15", 0),
    TIEMPO_SESION("", "", 1201_000),
    TIEMPO_SESION_ADM("", "", 601_000),
    TIEMPO_SESION_SUPER("", "", 601_000),
    INDICE_PING("REALIZAR PING", "PING", 1),
    VISOR_PAG1("ID PAGINA 0", "PG1", 0),
    VISOR_PAG2("ID PAGINA 1", "PG2", 1),
    CEDULA_DEFAULT("CEDULA TEMPORAL PARA CREACION", "1000000000", 1000000000),
    CADUCIDAD_CLAVE("TIEMPO DE CADUCIDAD DE CLAVES EN DIAS", "", 30),
    NUMERO_CLAVES_POR_DIA("NUMERO DE CLAVES AL DIA", "", 5),
    CADUCIDAD_MIN_CLAVE("TIEMPO MINIMO DE ACTUALIZACION DE CLAVES EN DIAS", "", 1),
    CARACTERES_ESPECIALES("CARACTERES ESPECIALES DE CLAVES", ",.-_", 30),
    HISTORIAL_CLAVES("HISTORIAL DE CLAVES", "", 12),
    CARACTERES_MIN_CLAVES("MINIMO DE CARACTERES EN LA CLAVE", "", 8),
    CARACTERES_MAX_CLAVES("MAXIMO DE CARACTERES EN LA CLAVE", "", 25),
    INTENTOS_FALLIDOS("INTENTOS DE LOGGEO PERMITIDO", "", 3);

    private final String descripcion;
    private final String codigo;
    private final Integer id;

    EstadosConfig(String _descripcion, String _codigo, Integer _id) {
        this.descripcion = _descripcion;
        this.codigo = _codigo;
        this.id = _id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public String getCodigo() {
        return codigo;
    }

    public Integer getId() {
        return id;
    }

}
