package ec.edu.monster.config;

/**
 *
 * @author guffenix
 */
public enum EstadosConfig {
//AMBIENTE
//    AMBIENTE("AMBIENTE DE DESARROLLO", "dev", 0),
//    AMBIENTE("AMBIENTE DE ACTUALIZACION BASE", "update", 0),
    //    AMBIENTE("AMBIENTE DE QA", "qa", 0),
//    AMBIENTE("DESARROLLO LOCAL - SISTEMA DE GESTIÓN DE RIESGOS", "pru", 0),//Activar DESARROLLO LOCAL UPDATES
    AMBIENTE("DESARROLLO - SISTEMA DE ", "dev", 0),//Activar DESARROLLO - CLOUD LOCAL
    //    AMBIENTE("PRE-PRODUCCIÓN Y QA - SISTEMA DE GESTIÓN DE RIESGOS", "desa", 0),//Activar DESARROLLO - CLOUD PRODUCTION
    //        AMBIENTE("PRE-PRODUCCIÓN Y QA - SISTEMA DE GESTIÓN DE RIESGOS", "pre", 0),//Activar produccion - LINUX EMAGIC
    //    AMBIENTE("SISTEMA DE GESTIÓN DE RIESGOS", "pro", 0),//Activar produccion LINUX
    //    AMBIENTE("PRE-PRODUCCION Y QA - SISTEMA DE GESTION DE RIESGOS", "pro", 0),//Activar Pre-Produccion WINDOWS
    //ARCHIVO_HIBERNATE("/hibernate." + EstadosConfig.AMBIENTE.codigo + ".cfg.xml", "hibernate." + EstadosConfig.AMBIENTE.codigo + ".cfg.xml", 0),
    ARCHIVO_HIBERNATE("/hibernate.cfg.xml", "hibernate.cfg.xml", 0),
    
    // AMBIENTES
    REPORTE("reporte/", "REPORTE", 0),
    UPLOAD("upload/", "UPLOAD", 0),
    TEMPLATE("template/", "TEMPLATE", 0),
    REGISTRO_LOG("log/", "REGISTRO_LOG", 0),
    LOGO("logo/", "LOGO", 0),
    //    PERFIL
    PERFIL_ACTIVO("PERFIL ACTIVO", "PAC", 0),
    PERFIL_DESACTIVADO("PERFIL DESACTIVADO", "DES", 0),
    PERFIL_SUPERADMINISTRADOR("PERFIL DE SUPER ADMINISTRADOR", "SPR", 0),
    PERFIL_MASTER_ADMINISTRADOR("PERFIL DE MASTER ADMINISTRADOR", "MAD", 0),
    PERFIL_ADMINISTRADOR("PERFIL DE ADMINISTRADOR ", "ADM", 0),
    PERFIL_REPORTERIA("PERFIL DE REPORTERIA", "REP", 0),
    USUARIO_ENTIDAD_ACTIVO("USUARIO ACTIVO POR ENTIDAD", "ACT", 0),
    //    PERMISO
    PERMISO_REGISTRADO("PERMISO REGISTRADO", "REG", 0),
    PERMISO_ACTIVO("PERMISO ACTIVO", "ACT", 0),
    PERMISO_INACTIVO("PERMISO INACTIVO", "DES", 0),
    ACTIVO("ACTIVADO", "ACT", 0),
    DESACTIVADO("DESACTIVADO", "DES", 0),
    PERMITE_DESCARGA("PERMITE DESCARGA", "DES", 0),
    NO_PERMITE_DESCARGA("NO PERMITE DESCARGA", "NDS", 0),
    BLOQUEADO("BLOQUEADO", "BLO", 0),
    DESHABILITADO("DESHABILITADO", "DHA", 0),
    HABILITADO("HABILITADO", "HAB", 0),
    ARCHIVADO("ARCHIVADO", "ARC", 0),
    DESARCHIVADO("DESARCHIVADO", "DAR", 0),
    ACTUALIZADO("ACTUALIZADO", "ACT", 0),
    LOGIN_EXITOSO("LOGIN EXITOSO", "PRI", 0),
    EXITOSO("REGISTRO EXITOSO", "SCC", 0),
    LOGIN_DESACTIVADO("LOGIN DESACTIVADO", "PDE", 0),
    LOGIN_SIN_PERFIL("LOGIN SIN PERFIL", "SPA", 0),
    //    RECURSO
    RECURSO_CODIGO_ORIGEN("RECURSO ORIGEN", "ORG", 0),
    RECURSO_OCULTO("OCULTO", "OCU", 0),
    RECURSO_CATEGORIA("IDENTIFICACION CATEGORIA", "0", 0),
    RECURSO_PLANTILLA("IDENTIFIICACION PLANTILLA", "1", 0),
    RECURSO_ORIGEN("IDENTIFIICACION YGGDRASIL", "6", 0),
    //    SUPER
    RECURSO_SUPERUSUARIO("IDENTIFIICACION SUPERUSUARIO", "SPR", 0),
    RECURSO_ADMIN("IDENTIFIICACION ADMIN", "ADM", 0),
    RECURSO_USUARIO("IDENTIFIICACION USUARIO", "APP", 0),
    //    USUARIO
    USUARIO_BLOQUEADO("USUARIO BLOQUEADO", "BLO", 0),
    USUARIO_ARCHIVADO("USUARIO ARCHIVADO", "ARC", 0),
    USUARIO_ACCESO_ACTIVADO("USUARIO ACCESO ACTIVADO", "ACT", 0),
    PRIMER_LOGUEO("PRIMER LOGUEO AL SISTEMA", "PRI", 0),
    ADMIN("ADMINISTRADOR", "ADM", 0),
    REPORTERIA("REPORTERIA", "USR", 0),
    ENTIDAD_EMAGIC("ENTIDAD EMAGIC", "700700700", 1234),
    ENTIDAD_ASOCIADA("ENTIDAD ASOCIADA", "ASO", 0),
    ENTIDAD_DESASOCIADA("ENTIDAD DESASOCIADA", "DES", 0),
    //    CLAVE
    CLAVE_USUARIO("CLAVE TIPO USUARIO", "USR", 0),
    CLAVE_REENVIADA("CLAVE TIPO REENVIO", "CAM", 0),
    CLAVE_CADUCADA("CLAVE CADUCADA", "CCA", 0),
    CLAVE_ERRONEA("CLAVE ERRONEA", "ERR", 0),
    CLAVE_ACTIVA("CLAVE ACTIVO", "ACT", 0),
    //    OFICINA
    OFICINA_DEFAULT("Consolidado", "000", 10_000),
    OFICINA_BENCHMARK("OFICINA BENCHMARK", "PUB", 7777777),
    OFICINA_ACTIVA("OFICINA ACTIVADA", "ACT", 0),
    OFICINA_DESACTIVADA("OFICINA DESACTIVADA", "DES", 0),
    ASIGNACION_ENTIDAD("ASIGNACIÓN ENTIDAD CON USUARIO", "ACT", 0),
    // TIPOS INFORMACION
    INFO_PUBLICA("INFORMACION PUBLICA", "PUB", 0),
    INFO_PRIVADA("INFORMACION PRIVADA", "PRI", 0),
    INFO_EMAGIC("INFORMACION EMAGIC", "EMG", 700700700),
    //    CORREO
    HOST_CORREO_NOTIFICACION("HOST_CORREO_NOTIFICACION", "mocha3012.mochahost.com", 0),
    PUERTO_CORREO_NOTIFICACION("PUERTO_CORREO_NOTIFICACION", "587", 0),
    USUARIO_CORREO_NOTIFICACION("USUARIO_CORREO_NOTIFICACION", "", 0),
    CLAVE_CORREO_NOTIFICACION("PASSWORD_CORREO_NOTIFICACION", "luis%2018", 0),
    CUENTA_CORREO_NOTIFICACION("CUENTA_CORREO_NOTIFICACION", "", 0),
    CUENTA_DESACTIVADA("CUENTA DESACTIVADA", "CDE", 0),
    MODO_NOTIFICACION_CORREO("CUENTA CORREO", "1", 0),
    //    PREFERENCIAS APP
    TIPO_APP("ESTADO TIPO APP", "APP", 0),
    APP_TEMA_ADM("TEMA AZUL CLARO", "azul-claro", 0),
    APP_LAYOUT_ADM("CAPAS AZUL CLARO, BOTONES, ETC", "azul-oscuro", 0),
    APP_TEMA_USER("TEMA AZUL OSCURO", "azul-claro", 0),
    APP_LAYOUT_USER("CAPAS AZUL OSCURO, BOTONES, ETC", "azul-claro", 0),
    APP_TEMA_SUPER("TEMA ROJO", "azul-claro", 0),
    APP_LAYOUT_SUPER("CAPAS ROJO, BOTONES, ETC", "rojo", 0),
    SIN_URL("RECURSO SIN URL", "NOURL", 0),
    //    CATALOGOS
    CATALOGO_APP("CATALOGO PARA APP", "APP", 0),
    CATALOGO_PUBLICO("CATALOGO PARA INFORMACION PUBLICA", "PUB", 2),
    CATALOGO_ESCENARIOS("CATALOGO PARA ESCENARIOS", "ESC", 3),
    CATALOGO_COMUN("CATALOGO GENERAL", "CMN", 0),
    CATALOGO_PAISES("CATALOGO POR PAIS", "PAIS", 0),
    //    JWT
    JWT_PRIMER_LOGUEO("TOKEN PRIMER LOGUEO", "1", 0),
    JWT_ACTUALIZADO("TOKEN ACTUALIZADO", "2", 0),
    JWT_BLOQUEADO("TOKEN BLOQUEADO", "3", 0),
    JWT_USUARIO_SUPERADM("TOKEN SUPER USUARIO", "4", 0),
    JWT_ACTIVO("TOKEN ACTIVO", "ACT", 0),
    JWT_OK("TOKEN CORRECTO", "", 0),
    JWT_KO("TOKEN INCORRECTO", "", -1),
    JWT_EXPIRADO("TOKEN EXPIRADO", "", 1),
    JWT_NO_SOPORTADO("TOKEN NO SOPORTADO", "", 2),
    JWT_MAL_GENERADO("TOKEN MAL GENERADO", "", 3),
    JWT_MAL_FIRMA("TOKEN MAL FIRMADO", "", 4),
    JWT_MAL_ARGUMENTOS("TOKEN CONTIENE MAL LOS ARGUMENTOS", "", 5),
    JWT_APP_OBSOLETO("TOKEN DEL APP OBSOLETO", "", 6),
    JWT_USUARIO("TOKEN DE USUARIO", "", 3),
    JWT_ADMIN("TOKEN DE ADMIN", "", 2),
    JWT_SUPER_ADMIN("TOKEN DE SUPER ADMINISTRADOR", "", 1),
    //Versionamiento
    VERSION_APP("Versión del Aplicativo", "1.0.15", 0),
    TIEMPO_SESION("", "", 1201_000),
    TIEMPO_SESION_ADM("", "", 601_000),
    TIEMPO_SESION_SUPER("", "", 601_000),
    INDICE_PING("REALIZAR PING", "PING", 1),
    VISOR_PAG1("ID PAGINA 0", "PG1", 0),
    VISOR_PAG2("ID PAGINA 1", "PG2", 1),
    CEDULA_DEFAULT("CEDULA TEMPORAL PARA CREACION", "1000000000", 1000000000),
    CADUCIDAD_CLAVE("TIEMPO DE CADUCIDAD DE CLAVES EN DIAS", "", 30),
    NUMERO_CLAVES_POR_DIA("NUMERO DE CLAVES AL DIA", "", 5),
    CADUCIDAD_MIN_CLAVE("TIEMPO MINIMO DE ACTUALIZACION DE CLAVES EN DIAS", "", 1),
    CARACTERES_ESPECIALES("CARACTERES ESPECIALES DE CLAVES", ",.-_", 30),
    HISTORIAL_CLAVES("HISTORIAL DE CLAVES", "", 12),
    CARACTERES_MIN_CLAVES("MINIMO DE CARACTERES EN LA CLAVE", "", 8),
    CARACTERES_MAX_CLAVES("MAXIMO DE CARACTERES EN LA CLAVE", "", 25),
    INTENTOS_FALLIDOS("INTENTOS DE LOGGEO PERMITIDO", "", 3);

    private final String descripcion;
    private final String codigo;
    private final Integer id;

    EstadosConfig(String _descripcion, String _codigo, Integer _id) {
        this.descripcion = _descripcion;
        this.codigo = _codigo;
        this.id = _id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public String getCodigo() {
        return codigo;
    }

    public Integer getId() {
        return id;
    }

}
