package ec.edu.saltos.modelo;
// Generated 12-ago-2020 14:57:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Descuento generated by hbm2java
 */
public class Descuento  implements java.io.Serializable {


     private int idDescuento;
     private String nombredes;
     private String descripciondes;
     private BigDecimal valordes;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Descuento() {
    }

	
    public Descuento(int idDescuento) {
        this.idDescuento = idDescuento;
    }
    public Descuento(int idDescuento, String nombredes, String descripciondes, BigDecimal valordes, Set<Pedido> pedidos) {
       this.idDescuento = idDescuento;
       this.nombredes = nombredes;
       this.descripciondes = descripciondes;
       this.valordes = valordes;
       this.pedidos = pedidos;
    }
   
    public int getIdDescuento() {
        return this.idDescuento;
    }
    
    public void setIdDescuento(int idDescuento) {
        this.idDescuento = idDescuento;
    }
    public String getNombredes() {
        return this.nombredes;
    }
    
    public void setNombredes(String nombredes) {
        this.nombredes = nombredes;
    }
    public String getDescripciondes() {
        return this.descripciondes;
    }
    
    public void setDescripciondes(String descripciondes) {
        this.descripciondes = descripciondes;
    }
    public BigDecimal getValordes() {
        return this.valordes;
    }
    
    public void setValordes(BigDecimal valordes) {
        this.valordes = valordes;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 47 * hash + this.idDescuento;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Descuento other = (Descuento) obj;
        if (this.idDescuento != other.idDescuento) {
            return false;
        }
        return true;
    }




}


