package ec.edu.saltos.modelo;
// Generated 12-ago-2020 14:57:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Objects;

/**
 * DetalleVuelo generated by hbm2java
 */
public class DetalleVuelo  implements java.io.Serializable {


     private Integer idDetvuelo;
     private Pedido pedido;
     private Vuelo vuelo;
     private BigDecimal costototal;

    public DetalleVuelo() {
    }

    public DetalleVuelo(Pedido pedido, Vuelo vuelo, BigDecimal costototal) {
       this.pedido = pedido;
       this.vuelo = vuelo;
       this.costototal = costototal;
    }
   
    public Integer getIdDetvuelo() {
        return this.idDetvuelo;
    }
    
    public void setIdDetvuelo(Integer idDetvuelo) {
        this.idDetvuelo = idDetvuelo;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Vuelo getVuelo() {
        return this.vuelo;
    }
    
    public void setVuelo(Vuelo vuelo) {
        this.vuelo = vuelo;
    }
    public BigDecimal getCostototal() {
        return this.costototal;
    }
    
    public void setCostototal(BigDecimal costototal) {
        this.costototal = costototal;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + Objects.hashCode(this.idDetvuelo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final DetalleVuelo other = (DetalleVuelo) obj;
        if (!Objects.equals(this.idDetvuelo, other.idDetvuelo)) {
            return false;
        }
        return true;
    }




}


