package ec.edu.saltos.modelo;
// Generated 12-ago-2020 14:57:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int idEmpleado;
     private String nombresemp;
     private String apellidosemp;
     private String cedulaemp;
     private String telfemp;
     private String correoemp;
     private String cargoemp;
     private Date fechanacimiento;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Empleado() {
    }

	
    public Empleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Empleado(int idEmpleado, String nombresemp, String apellidosemp, String cedulaemp, String telfemp, String correoemp, String cargoemp, Date fechanacimiento, Set<Usuario> usuarios) {
       this.idEmpleado = idEmpleado;
       this.nombresemp = nombresemp;
       this.apellidosemp = apellidosemp;
       this.cedulaemp = cedulaemp;
       this.telfemp = telfemp;
       this.correoemp = correoemp;
       this.cargoemp = cargoemp;
       this.fechanacimiento = fechanacimiento;
       this.usuarios = usuarios;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombresemp() {
        return this.nombresemp;
    }
    
    public void setNombresemp(String nombresemp) {
        this.nombresemp = nombresemp;
    }
    public String getApellidosemp() {
        return this.apellidosemp;
    }
    
    public void setApellidosemp(String apellidosemp) {
        this.apellidosemp = apellidosemp;
    }
    public String getCedulaemp() {
        return this.cedulaemp;
    }
    
    public void setCedulaemp(String cedulaemp) {
        this.cedulaemp = cedulaemp;
    }
    public String getTelfemp() {
        return this.telfemp;
    }
    
    public void setTelfemp(String telfemp) {
        this.telfemp = telfemp;
    }
    public String getCorreoemp() {
        return this.correoemp;
    }
    
    public void setCorreoemp(String correoemp) {
        this.correoemp = correoemp;
    }
    public String getCargoemp() {
        return this.cargoemp;
    }
    
    public void setCargoemp(String cargoemp) {
        this.cargoemp = cargoemp;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 37 * hash + this.idEmpleado;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Empleado other = (Empleado) obj;
        if (this.idEmpleado != other.idEmpleado) {
            return false;
        }
        return true;
    }




}


