package ec.edu.saltos.modelo;
// Generated 12-ago-2020 14:57:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FormacionParacaidista generated by hbm2java
 */
public class FormacionParacaidista  implements java.io.Serializable {


     private int idForpar;
     private String nombrecurso;
     private Date fechainiciocurso;
     private Date fechafincurso;
     private String lugarcurso;
     private Set<Paracaidista> paracaidistas = new HashSet<Paracaidista>(0);

    public FormacionParacaidista() {
    }

	
    public FormacionParacaidista(int idForpar) {
        this.idForpar = idForpar;
    }
    public FormacionParacaidista(int idForpar, String nombrecurso, Date fechainiciocurso, Date fechafincurso, String lugarcurso, Set<Paracaidista> paracaidistas) {
       this.idForpar = idForpar;
       this.nombrecurso = nombrecurso;
       this.fechainiciocurso = fechainiciocurso;
       this.fechafincurso = fechafincurso;
       this.lugarcurso = lugarcurso;
       this.paracaidistas = paracaidistas;
    }
   
    public int getIdForpar() {
        return this.idForpar;
    }
    
    public void setIdForpar(int idForpar) {
        this.idForpar = idForpar;
    }
    public String getNombrecurso() {
        return this.nombrecurso;
    }
    
    public void setNombrecurso(String nombrecurso) {
        this.nombrecurso = nombrecurso;
    }
    public Date getFechainiciocurso() {
        return this.fechainiciocurso;
    }
    
    public void setFechainiciocurso(Date fechainiciocurso) {
        this.fechainiciocurso = fechainiciocurso;
    }
    public Date getFechafincurso() {
        return this.fechafincurso;
    }
    
    public void setFechafincurso(Date fechafincurso) {
        this.fechafincurso = fechafincurso;
    }
    public String getLugarcurso() {
        return this.lugarcurso;
    }
    
    public void setLugarcurso(String lugarcurso) {
        this.lugarcurso = lugarcurso;
    }
    public Set<Paracaidista> getParacaidistas() {
        return this.paracaidistas;
    }
    
    public void setParacaidistas(Set<Paracaidista> paracaidistas) {
        this.paracaidistas = paracaidistas;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + this.idForpar;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FormacionParacaidista other = (FormacionParacaidista) obj;
        if (this.idForpar != other.idForpar) {
            return false;
        }
        return true;
    }




}


