package ec.edu.saltos.modelo;
// Generated 12-ago-2020 14:57:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Paracaidista generated by hbm2java
 */
public class Paracaidista  implements java.io.Serializable {


     private Integer idParacaidista;
     private FormacionParacaidista formacionParacaidista;
     private String nombrespar;
     private String apellidospar;
     private String tipopar;
     private String escuelaformacion;
     private Integer numerosaltos;
     private Date fechaultimosalto;
     private Boolean licencia;
     private Date fechacaducidadlicencia;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Paracaidista() {
    }

    public Paracaidista(FormacionParacaidista formacionParacaidista, String nombrespar, String apellidospar, String tipopar, String escuelaformacion, Integer numerosaltos, Date fechaultimosalto, Boolean licencia, Date fechacaducidadlicencia, Set<Pedido> pedidos) {
       this.formacionParacaidista = formacionParacaidista;
       this.nombrespar = nombrespar;
       this.apellidospar = apellidospar;
       this.tipopar = tipopar;
       this.escuelaformacion = escuelaformacion;
       this.numerosaltos = numerosaltos;
       this.fechaultimosalto = fechaultimosalto;
       this.licencia = licencia;
       this.fechacaducidadlicencia = fechacaducidadlicencia;
       this.pedidos = pedidos;
    }
   
    public Integer getIdParacaidista() {
        return this.idParacaidista;
    }
    
    public void setIdParacaidista(Integer idParacaidista) {
        this.idParacaidista = idParacaidista;
    }
    public FormacionParacaidista getFormacionParacaidista() {
        return this.formacionParacaidista;
    }
    
    public void setFormacionParacaidista(FormacionParacaidista formacionParacaidista) {
        this.formacionParacaidista = formacionParacaidista;
    }
    public String getNombrespar() {
        return this.nombrespar;
    }
    
    public void setNombrespar(String nombrespar) {
        this.nombrespar = nombrespar;
    }
    public String getApellidospar() {
        return this.apellidospar;
    }
    
    public void setApellidospar(String apellidospar) {
        this.apellidospar = apellidospar;
    }
    public String getTipopar() {
        return this.tipopar;
    }
    
    public void setTipopar(String tipopar) {
        this.tipopar = tipopar;
    }
    public String getEscuelaformacion() {
        return this.escuelaformacion;
    }
    
    public void setEscuelaformacion(String escuelaformacion) {
        this.escuelaformacion = escuelaformacion;
    }
    public Integer getNumerosaltos() {
        return this.numerosaltos;
    }
    
    public void setNumerosaltos(Integer numerosaltos) {
        this.numerosaltos = numerosaltos;
    }
    public Date getFechaultimosalto() {
        return this.fechaultimosalto;
    }
    
    public void setFechaultimosalto(Date fechaultimosalto) {
        this.fechaultimosalto = fechaultimosalto;
    }
    public Boolean getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(Boolean licencia) {
        this.licencia = licencia;
    }
    public Date getFechacaducidadlicencia() {
        return this.fechacaducidadlicencia;
    }
    
    public void setFechacaducidadlicencia(Date fechacaducidadlicencia) {
        this.fechacaducidadlicencia = fechacaducidadlicencia;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + Objects.hashCode(this.idParacaidista);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Paracaidista other = (Paracaidista) obj;
        if (!Objects.equals(this.idParacaidista, other.idParacaidista)) {
            return false;
        }
        return true;
    }




}


