package ec.edu.saltos.modelo;
// Generated 12-ago-2020 14:57:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Piloto generated by hbm2java
 */
public class Piloto  implements java.io.Serializable {


     private int idPiloto;
     private String nombrespil;
     private String cedulapil;
     private String telfpil;
     private Set<Vuelo> vuelos = new HashSet<Vuelo>(0);

    public Piloto() {
    }

	
    public Piloto(int idPiloto) {
        this.idPiloto = idPiloto;
    }
    public Piloto(int idPiloto, String nombrespil, String cedulapil, String telfpil, Set<Vuelo> vuelos) {
       this.idPiloto = idPiloto;
       this.nombrespil = nombrespil;
       this.cedulapil = cedulapil;
       this.telfpil = telfpil;
       this.vuelos = vuelos;
    }
   
    public int getIdPiloto() {
        return this.idPiloto;
    }
    
    public void setIdPiloto(int idPiloto) {
        this.idPiloto = idPiloto;
    }
    public String getNombrespil() {
        return this.nombrespil;
    }
    
    public void setNombrespil(String nombrespil) {
        this.nombrespil = nombrespil;
    }
    public String getCedulapil() {
        return this.cedulapil;
    }
    
    public void setCedulapil(String cedulapil) {
        this.cedulapil = cedulapil;
    }
    public String getTelfpil() {
        return this.telfpil;
    }
    
    public void setTelfpil(String telfpil) {
        this.telfpil = telfpil;
    }
    public Set<Vuelo> getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(Set<Vuelo> vuelos) {
        this.vuelos = vuelos;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 43 * hash + this.idPiloto;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Piloto other = (Piloto) obj;
        if (this.idPiloto != other.idPiloto) {
            return false;
        }
        return true;
    }

    


}


