package ec.edu.saltos.modelo;
// Generated 12-ago-2020 14:57:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Responsable generated by hbm2java
 */
public class Responsable  implements java.io.Serializable {


     private int idResponsable;
     private String nombresres;
     private String cedulares;
     private String emailres;
     private String telfres;
     private Set<ServicioAdicional> servicioAdicionals = new HashSet<ServicioAdicional>(0);

    public Responsable() {
    }

	
    public Responsable(int idResponsable) {
        this.idResponsable = idResponsable;
    }
    public Responsable(int idResponsable, String nombresres, String cedulares, String emailres, String telfres, Set<ServicioAdicional> servicioAdicionals) {
       this.idResponsable = idResponsable;
       this.nombresres = nombresres;
       this.cedulares = cedulares;
       this.emailres = emailres;
       this.telfres = telfres;
       this.servicioAdicionals = servicioAdicionals;
    }
   
    public int getIdResponsable() {
        return this.idResponsable;
    }
    
    public void setIdResponsable(int idResponsable) {
        this.idResponsable = idResponsable;
    }
    public String getNombresres() {
        return this.nombresres;
    }
    
    public void setNombresres(String nombresres) {
        this.nombresres = nombresres;
    }
    public String getCedulares() {
        return this.cedulares;
    }
    
    public void setCedulares(String cedulares) {
        this.cedulares = cedulares;
    }
    public String getEmailres() {
        return this.emailres;
    }
    
    public void setEmailres(String emailres) {
        this.emailres = emailres;
    }
    public String getTelfres() {
        return this.telfres;
    }
    
    public void setTelfres(String telfres) {
        this.telfres = telfres;
    }
    public Set<ServicioAdicional> getServicioAdicionals() {
        return this.servicioAdicionals;
    }
    
    public void setServicioAdicionals(Set<ServicioAdicional> servicioAdicionals) {
        this.servicioAdicionals = servicioAdicionals;
    }




}


