package ec.edu.saltos.modelo;
// Generated 12-ago-2020 14:57:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Salto generated by hbm2java
 */
public class Salto  implements java.io.Serializable {


     private int idSalto;
     private String tiposalto;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Salto() {
    }

	
    public Salto(int idSalto) {
        this.idSalto = idSalto;
    }
    public Salto(int idSalto, String tiposalto, Set<Pedido> pedidos) {
       this.idSalto = idSalto;
       this.tiposalto = tiposalto;
       this.pedidos = pedidos;
    }
   
    public int getIdSalto() {
        return this.idSalto;
    }
    
    public void setIdSalto(int idSalto) {
        this.idSalto = idSalto;
    }
    public String getTiposalto() {
        return this.tiposalto;
    }
    
    public void setTiposalto(String tiposalto) {
        this.tiposalto = tiposalto;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


