package ec.edu.saltos.modelo;
// Generated 12-ago-2020 14:57:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Vuelo generated by hbm2java
 */
public class Vuelo  implements java.io.Serializable {


     private Integer idVuelo;
     private Aeronave aeronave;
     private Piloto piloto;
     private Date horasalida;
     private Date horallegada;
     private Integer capacidadpersonas;
     private Set<DetalleVuelo> detalleVuelos = new HashSet<DetalleVuelo>(0);

    public Vuelo() {
    }

    public Vuelo(Aeronave aeronave, Piloto piloto, Date horasalida, Date horallegada, Integer capacidadpersonas, Set<DetalleVuelo> detalleVuelos) {
       this.aeronave = aeronave;
       this.piloto = piloto;
       this.horasalida = horasalida;
       this.horallegada = horallegada;
       this.capacidadpersonas = capacidadpersonas;
       this.detalleVuelos = detalleVuelos;
    }
   
    public Integer getIdVuelo() {
        return this.idVuelo;
    }
    
    public void setIdVuelo(Integer idVuelo) {
        this.idVuelo = idVuelo;
    }
    public Aeronave getAeronave() {
        return this.aeronave;
    }
    
    public void setAeronave(Aeronave aeronave) {
        this.aeronave = aeronave;
    }
    public Piloto getPiloto() {
        return this.piloto;
    }
    
    public void setPiloto(Piloto piloto) {
        this.piloto = piloto;
    }
    public Date getHorasalida() {
        return this.horasalida;
    }
    
    public void setHorasalida(Date horasalida) {
        this.horasalida = horasalida;
    }
    public Date getHorallegada() {
        return this.horallegada;
    }
    
    public void setHorallegada(Date horallegada) {
        this.horallegada = horallegada;
    }
    public Integer getCapacidadpersonas() {
        return this.capacidadpersonas;
    }
    
    public void setCapacidadpersonas(Integer capacidadpersonas) {
        this.capacidadpersonas = capacidadpersonas;
    }
    public Set<DetalleVuelo> getDetalleVuelos() {
        return this.detalleVuelos;
    }
    
    public void setDetalleVuelos(Set<DetalleVuelo> detalleVuelos) {
        this.detalleVuelos = detalleVuelos;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 47 * hash + Objects.hashCode(this.idVuelo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Vuelo other = (Vuelo) obj;
        if (!Objects.equals(this.idVuelo, other.idVuelo)) {
            return false;
        }
        return true;
    }




}


