package ec.edu.saltos.modelo;
// Generated 09-ago-2020 23:23:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aeronave generated by hbm2java
 */
public class Aeronave  implements java.io.Serializable {


     private int idaeronave;
     private String nombreaer;
     private String modeloaer;
     private Integer capacidadtotalaer;
     private Set<Vuelo> vuelos = new HashSet<Vuelo>(0);

    public Aeronave() {
    }

	
    public Aeronave(int idaeronave) {
        this.idaeronave = idaeronave;
    }
    public Aeronave(int idaeronave, String nombreaer, String modeloaer, Integer capacidadtotalaer, Set<Vuelo> vuelos) {
       this.idaeronave = idaeronave;
       this.nombreaer = nombreaer;
       this.modeloaer = modeloaer;
       this.capacidadtotalaer = capacidadtotalaer;
       this.vuelos = vuelos;
    }
   
    public int getIdaeronave() {
        return this.idaeronave;
    }
    
    public void setIdaeronave(int idaeronave) {
        this.idaeronave = idaeronave;
    }
    public String getNombreaer() {
        return this.nombreaer;
    }
    
    public void setNombreaer(String nombreaer) {
        this.nombreaer = nombreaer;
    }
    public String getModeloaer() {
        return this.modeloaer;
    }
    
    public void setModeloaer(String modeloaer) {
        this.modeloaer = modeloaer;
    }
    public Integer getCapacidadtotalaer() {
        return this.capacidadtotalaer;
    }
    
    public void setCapacidadtotalaer(Integer capacidadtotalaer) {
        this.capacidadtotalaer = capacidadtotalaer;
    }
    public Set<Vuelo> getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(Set<Vuelo> vuelos) {
        this.vuelos = vuelos;
    }

    @Override
    public String toString() {
        return "Aeronave{" + "idaeronave=" + idaeronave + ", nombreaer=" + nombreaer + ", modeloaer=" + modeloaer + ", capacidadtotalaer=" + capacidadtotalaer + '}';
    }

    
}


