package ec.edu.saltos.modelo;
// Generated 09-ago-2020 23:23:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idcliente;
     private String nombrescli;
     private String apellidoscli;
     private String cedulacli;
     private Date fechanacimientocli;
     private String correocli;
     private String telfcli;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Cliente() {
    }

	
    public Cliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public Cliente(int idcliente, String nombrescli, String apellidoscli, String cedulacli, Date fechanacimientocli, String correocli, String telfcli, Set<Pedido> pedidos) {
       this.idcliente = idcliente;
       this.nombrescli = nombrescli;
       this.apellidoscli = apellidoscli;
       this.cedulacli = cedulacli;
       this.fechanacimientocli = fechanacimientocli;
       this.correocli = correocli;
       this.telfcli = telfcli;
       this.pedidos = pedidos;
    }
   
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public String getNombrescli() {
        return this.nombrescli;
    }
    
    public void setNombrescli(String nombrescli) {
        this.nombrescli = nombrescli;
    }
    public String getApellidoscli() {
        return this.apellidoscli;
    }
    
    public void setApellidoscli(String apellidoscli) {
        this.apellidoscli = apellidoscli;
    }
    public String getCedulacli() {
        return this.cedulacli;
    }
    
    public void setCedulacli(String cedulacli) {
        this.cedulacli = cedulacli;
    }
    public Date getFechanacimientocli() {
        return this.fechanacimientocli;
    }
    
    public void setFechanacimientocli(Date fechanacimientocli) {
        this.fechanacimientocli = fechanacimientocli;
    }
    public String getCorreocli() {
        return this.correocli;
    }
    
    public void setCorreocli(String correocli) {
        this.correocli = correocli;
    }
    public String getTelfcli() {
        return this.telfcli;
    }
    
    public void setTelfcli(String telfcli) {
        this.telfcli = telfcli;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


