package ec.edu.saltos.modelo;
// Generated 09-ago-2020 23:23:27 by Hibernate Tools 4.3.1



/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private Integer idpermiso;
     private Perfil perfil;
     private Recurso recurso;
     private String nombreper;
     private String estadoper;

    public Permiso() {
    }

    public Permiso(Perfil perfil, Recurso recurso, String nombreper, String estadoper) {
       this.perfil = perfil;
       this.recurso = recurso;
       this.nombreper = nombreper;
       this.estadoper = estadoper;
    }
   
    public Integer getIdpermiso() {
        return this.idpermiso;
    }
    
    public void setIdpermiso(Integer idpermiso) {
        this.idpermiso = idpermiso;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Recurso getRecurso() {
        return this.recurso;
    }
    
    public void setRecurso(Recurso recurso) {
        this.recurso = recurso;
    }
    public String getNombreper() {
        return this.nombreper;
    }
    
    public void setNombreper(String nombreper) {
        this.nombreper = nombreper;
    }
    public String getEstadoper() {
        return this.estadoper;
    }
    
    public void setEstadoper(String estadoper) {
        this.estadoper = estadoper;
    }




}


