package ec.edu.saltos.modelo;
// Generated 09-ago-2020 23:23:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Piloto generated by hbm2java
 */
public class Piloto  implements java.io.Serializable {


     private int idpiloto;
     private String nombrespil;
     private String cedulapil;
     private String telfpil;
     private Set<Vuelo> vuelos = new HashSet<Vuelo>(0);

    public Piloto() {
    }

	
    public Piloto(int idpiloto) {
        this.idpiloto = idpiloto;
    }
    public Piloto(int idpiloto, String nombrespil, String cedulapil, String telfpil, Set<Vuelo> vuelos) {
       this.idpiloto = idpiloto;
       this.nombrespil = nombrespil;
       this.cedulapil = cedulapil;
       this.telfpil = telfpil;
       this.vuelos = vuelos;
    }
   
    public int getIdpiloto() {
        return this.idpiloto;
    }
    
    public void setIdpiloto(int idpiloto) {
        this.idpiloto = idpiloto;
    }
    public String getNombrespil() {
        return this.nombrespil;
    }
    
    public void setNombrespil(String nombrespil) {
        this.nombrespil = nombrespil;
    }
    public String getCedulapil() {
        return this.cedulapil;
    }
    
    public void setCedulapil(String cedulapil) {
        this.cedulapil = cedulapil;
    }
    public String getTelfpil() {
        return this.telfpil;
    }
    
    public void setTelfpil(String telfpil) {
        this.telfpil = telfpil;
    }
    public Set<Vuelo> getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(Set<Vuelo> vuelos) {
        this.vuelos = vuelos;
    }




}


