package ec.edu.saltos.modelo;
// Generated 09-ago-2020 23:23:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Salto generated by hbm2java
 */
public class Salto  implements java.io.Serializable {


     private int idsalto;
     private String tiposalto;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Salto() {
    }

	
    public Salto(int idsalto) {
        this.idsalto = idsalto;
    }
    public Salto(int idsalto, String tiposalto, Set<Pedido> pedidos) {
       this.idsalto = idsalto;
       this.tiposalto = tiposalto;
       this.pedidos = pedidos;
    }
   
    public int getIdsalto() {
        return this.idsalto;
    }
    
    public void setIdsalto(int idsalto) {
        this.idsalto = idsalto;
    }
    public String getTiposalto() {
        return this.tiposalto;
    }
    
    public void setTiposalto(String tiposalto) {
        this.tiposalto = tiposalto;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


