package ec.edu.saltos.modelo;
// Generated 09-ago-2020 23:23:27 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ServicioAdicional generated by hbm2java
 */
public class ServicioAdicional  implements java.io.Serializable {


     private Integer idservicio;
     private Responsable responsable;
     private String nombreser;
     private String descripcionser;
     private BigDecimal costoser;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public ServicioAdicional() {
    }

    public ServicioAdicional(Responsable responsable, String nombreser, String descripcionser, BigDecimal costoser, Set<Pedido> pedidos) {
       this.responsable = responsable;
       this.nombreser = nombreser;
       this.descripcionser = descripcionser;
       this.costoser = costoser;
       this.pedidos = pedidos;
    }
   
    public Integer getIdservicio() {
        return this.idservicio;
    }
    
    public void setIdservicio(Integer idservicio) {
        this.idservicio = idservicio;
    }
    public Responsable getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(Responsable responsable) {
        this.responsable = responsable;
    }
    public String getNombreser() {
        return this.nombreser;
    }
    
    public void setNombreser(String nombreser) {
        this.nombreser = nombreser;
    }
    public String getDescripcionser() {
        return this.descripcionser;
    }
    
    public void setDescripcionser(String descripcionser) {
        this.descripcionser = descripcionser;
    }
    public BigDecimal getCostoser() {
        return this.costoser;
    }
    
    public void setCostoser(BigDecimal costoser) {
        this.costoser = costoser;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


