package ec.edu.saltos.modelo;
// Generated 09-ago-2020 23:23:27 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private Empleado empleado;
     private Perfil perfil;
     private String nombreusuario;
     private String claveusu;

    public Usuario() {
    }

    public Usuario(Empleado empleado, Perfil perfil, String nombreusuario, String claveusu) {
       this.empleado = empleado;
       this.perfil = perfil;
       this.nombreusuario = nombreusuario;
       this.claveusu = claveusu;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getClaveusu() {
        return this.claveusu;
    }
    
    public void setClaveusu(String claveusu) {
        this.claveusu = claveusu;
    }




}


