package ec.edu.saltos.modelo;
// Generated 18-ago-2020 23:39:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AsignarPerfil generated by hbm2java
 */
public class AsignarPerfil  implements java.io.Serializable {


     private Integer idAsignarPerfil;
     private Perfil perfil;
     private UsuarioAcceso usuarioAcceso;
     private Date asginarPerfilFecha;

    public AsignarPerfil() {
    }

    public AsignarPerfil(Perfil perfil, UsuarioAcceso usuarioAcceso, Date asginarPerfilFecha) {
       this.perfil = perfil;
       this.usuarioAcceso = usuarioAcceso;
       this.asginarPerfilFecha = asginarPerfilFecha;
    }
   
    public Integer getIdAsignarPerfil() {
        return this.idAsignarPerfil;
    }
    
    public void setIdAsignarPerfil(Integer idAsignarPerfil) {
        this.idAsignarPerfil = idAsignarPerfil;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public UsuarioAcceso getUsuarioAcceso() {
        return this.usuarioAcceso;
    }
    
    public void setUsuarioAcceso(UsuarioAcceso usuarioAcceso) {
        this.usuarioAcceso = usuarioAcceso;
    }
    public Date getAsginarPerfilFecha() {
        return this.asginarPerfilFecha;
    }
    
    public void setAsginarPerfilFecha(Date asginarPerfilFecha) {
        this.asginarPerfilFecha = asginarPerfilFecha;
    }




}


