package ec.edu.saltos.modelo;
// Generated 18-ago-2020 23:39:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ConfigClave generated by hbm2java
 */
public class ConfigClave  implements java.io.Serializable {


     private int idConfigClave;
     private Integer claveCharMax;
     private Integer claveCharMin;
     private Boolean claveCharAlfanumerico;
     private Boolean claveCharMayus;
     private Boolean claveCharMinus;
     private Boolean claveCharEspecial;
     private String claveStrEspecial;
     private Date claveFecha;
     private Date claveFechaMod;
     private Integer claveCambiosDia;
     private Integer claveIntentosFallidos;
     private String claveUltimo;
     private Set<UsuarioAcceso> usuarioAccesos = new HashSet<UsuarioAcceso>(0);

    public ConfigClave() {
    }

	
    public ConfigClave(int idConfigClave) {
        this.idConfigClave = idConfigClave;
    }
    public ConfigClave(int idConfigClave, Integer claveCharMax, Integer claveCharMin, Boolean claveCharAlfanumerico, Boolean claveCharMayus, Boolean claveCharMinus, Boolean claveCharEspecial, String claveStrEspecial, Date claveFecha, Date claveFechaMod, Integer claveCambiosDia, Integer claveIntentosFallidos, String claveUltimo, Set<UsuarioAcceso> usuarioAccesos) {
       this.idConfigClave = idConfigClave;
       this.claveCharMax = claveCharMax;
       this.claveCharMin = claveCharMin;
       this.claveCharAlfanumerico = claveCharAlfanumerico;
       this.claveCharMayus = claveCharMayus;
       this.claveCharMinus = claveCharMinus;
       this.claveCharEspecial = claveCharEspecial;
       this.claveStrEspecial = claveStrEspecial;
       this.claveFecha = claveFecha;
       this.claveFechaMod = claveFechaMod;
       this.claveCambiosDia = claveCambiosDia;
       this.claveIntentosFallidos = claveIntentosFallidos;
       this.claveUltimo = claveUltimo;
       this.usuarioAccesos = usuarioAccesos;
    }
   
    public int getIdConfigClave() {
        return this.idConfigClave;
    }
    
    public void setIdConfigClave(int idConfigClave) {
        this.idConfigClave = idConfigClave;
    }
    public Integer getClaveCharMax() {
        return this.claveCharMax;
    }
    
    public void setClaveCharMax(Integer claveCharMax) {
        this.claveCharMax = claveCharMax;
    }
    public Integer getClaveCharMin() {
        return this.claveCharMin;
    }
    
    public void setClaveCharMin(Integer claveCharMin) {
        this.claveCharMin = claveCharMin;
    }
    public Boolean getClaveCharAlfanumerico() {
        return this.claveCharAlfanumerico;
    }
    
    public void setClaveCharAlfanumerico(Boolean claveCharAlfanumerico) {
        this.claveCharAlfanumerico = claveCharAlfanumerico;
    }
    public Boolean getClaveCharMayus() {
        return this.claveCharMayus;
    }
    
    public void setClaveCharMayus(Boolean claveCharMayus) {
        this.claveCharMayus = claveCharMayus;
    }
    public Boolean getClaveCharMinus() {
        return this.claveCharMinus;
    }
    
    public void setClaveCharMinus(Boolean claveCharMinus) {
        this.claveCharMinus = claveCharMinus;
    }
    public Boolean getClaveCharEspecial() {
        return this.claveCharEspecial;
    }
    
    public void setClaveCharEspecial(Boolean claveCharEspecial) {
        this.claveCharEspecial = claveCharEspecial;
    }
    public String getClaveStrEspecial() {
        return this.claveStrEspecial;
    }
    
    public void setClaveStrEspecial(String claveStrEspecial) {
        this.claveStrEspecial = claveStrEspecial;
    }
    public Date getClaveFecha() {
        return this.claveFecha;
    }
    
    public void setClaveFecha(Date claveFecha) {
        this.claveFecha = claveFecha;
    }
    public Date getClaveFechaMod() {
        return this.claveFechaMod;
    }
    
    public void setClaveFechaMod(Date claveFechaMod) {
        this.claveFechaMod = claveFechaMod;
    }
    public Integer getClaveCambiosDia() {
        return this.claveCambiosDia;
    }
    
    public void setClaveCambiosDia(Integer claveCambiosDia) {
        this.claveCambiosDia = claveCambiosDia;
    }
    public Integer getClaveIntentosFallidos() {
        return this.claveIntentosFallidos;
    }
    
    public void setClaveIntentosFallidos(Integer claveIntentosFallidos) {
        this.claveIntentosFallidos = claveIntentosFallidos;
    }
    public String getClaveUltimo() {
        return this.claveUltimo;
    }
    
    public void setClaveUltimo(String claveUltimo) {
        this.claveUltimo = claveUltimo;
    }
    public Set<UsuarioAcceso> getUsuarioAccesos() {
        return this.usuarioAccesos;
    }
    
    public void setUsuarioAccesos(Set<UsuarioAcceso> usuarioAccesos) {
        this.usuarioAccesos = usuarioAccesos;
    }




}


