package ec.edu.saltos.modelo;
// Generated 18-ago-2020 23:39:25 by Hibernate Tools 4.3.1



/**
 * OpcionPerfil generated by hbm2java
 */
public class OpcionPerfil  implements java.io.Serializable {


     private Integer idPermiso;
     private Opcion opcion;
     private Perfil perfil;
     private String opcPerEstatus;

    public OpcionPerfil() {
    }

    public OpcionPerfil(Opcion opcion, Perfil perfil, String opcPerEstatus) {
       this.opcion = opcion;
       this.perfil = perfil;
       this.opcPerEstatus = opcPerEstatus;
    }
   
    public Integer getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(Integer idPermiso) {
        this.idPermiso = idPermiso;
    }
    public Opcion getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(Opcion opcion) {
        this.opcion = opcion;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getOpcPerEstatus() {
        return this.opcPerEstatus;
    }
    
    public void setOpcPerEstatus(String opcPerEstatus) {
        this.opcPerEstatus = opcPerEstatus;
    }




}


