package ec.edu.saltos.modelo;
// Generated 18-ago-2020 23:39:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Opcion generated by hbm2java
 */
public class Opcion  implements java.io.Serializable {


     private Integer idOpcion;
     private Opcion opcion;
     private String recNombre;
     private String recDescripcion;
     private String recPagina;
     private String recEstatus;
     private Integer recIndex;
     private Set<OpcionPerfil> opcionPerfils = new HashSet<OpcionPerfil>(0);
     private Set<Opcion> opcions = new HashSet<Opcion>(0);

    public Opcion() {
    }

    public Opcion(Opcion opcion, String recNombre, String recDescripcion, String recPagina, String recEstatus, Integer recIndex, Set<OpcionPerfil> opcionPerfils, Set<Opcion> opcions) {
       this.opcion = opcion;
       this.recNombre = recNombre;
       this.recDescripcion = recDescripcion;
       this.recPagina = recPagina;
       this.recEstatus = recEstatus;
       this.recIndex = recIndex;
       this.opcionPerfils = opcionPerfils;
       this.opcions = opcions;
    }
   
    public Integer getIdOpcion() {
        return this.idOpcion;
    }
    
    public void setIdOpcion(Integer idOpcion) {
        this.idOpcion = idOpcion;
    }
    public Opcion getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(Opcion opcion) {
        this.opcion = opcion;
    }
    public String getRecNombre() {
        return this.recNombre;
    }
    
    public void setRecNombre(String recNombre) {
        this.recNombre = recNombre;
    }
    public String getRecDescripcion() {
        return this.recDescripcion;
    }
    
    public void setRecDescripcion(String recDescripcion) {
        this.recDescripcion = recDescripcion;
    }
    public String getRecPagina() {
        return this.recPagina;
    }
    
    public void setRecPagina(String recPagina) {
        this.recPagina = recPagina;
    }
    public String getRecEstatus() {
        return this.recEstatus;
    }
    
    public void setRecEstatus(String recEstatus) {
        this.recEstatus = recEstatus;
    }
    public Integer getRecIndex() {
        return this.recIndex;
    }
    
    public void setRecIndex(Integer recIndex) {
        this.recIndex = recIndex;
    }
    public Set<OpcionPerfil> getOpcionPerfils() {
        return this.opcionPerfils;
    }
    
    public void setOpcionPerfils(Set<OpcionPerfil> opcionPerfils) {
        this.opcionPerfils = opcionPerfils;
    }
    public Set<Opcion> getOpcions() {
        return this.opcions;
    }
    
    public void setOpcions(Set<Opcion> opcions) {
        this.opcions = opcions;
    }




}


