package ec.edu.saltos.modelo;
// Generated 18-ago-2020 23:39:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idUsuario;
     private String usrNombres;
     private String usrApellidos;
     private String usrDireccion;
     private String usrIdentificacion;
     private Date usrFechaNacimiento;
     private String usrTelefono;
     private String usrCorreo;
     private String usrFoto;
     private Date usrFechaCreacion;
     private Date usrFechaMod;
     private Set<UsuarioAcceso> usuarioAccesos = new HashSet<UsuarioAcceso>(0);

    public Persona() {
    }

	
    public Persona(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Persona(int idUsuario, String usrNombres, String usrApellidos, String usrDireccion, String usrIdentificacion, Date usrFechaNacimiento, String usrTelefono, String usrCorreo, String usrFoto, Date usrFechaCreacion, Date usrFechaMod, Set<UsuarioAcceso> usuarioAccesos) {
       this.idUsuario = idUsuario;
       this.usrNombres = usrNombres;
       this.usrApellidos = usrApellidos;
       this.usrDireccion = usrDireccion;
       this.usrIdentificacion = usrIdentificacion;
       this.usrFechaNacimiento = usrFechaNacimiento;
       this.usrTelefono = usrTelefono;
       this.usrCorreo = usrCorreo;
       this.usrFoto = usrFoto;
       this.usrFechaCreacion = usrFechaCreacion;
       this.usrFechaMod = usrFechaMod;
       this.usuarioAccesos = usuarioAccesos;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUsrNombres() {
        return this.usrNombres;
    }
    
    public void setUsrNombres(String usrNombres) {
        this.usrNombres = usrNombres;
    }
    public String getUsrApellidos() {
        return this.usrApellidos;
    }
    
    public void setUsrApellidos(String usrApellidos) {
        this.usrApellidos = usrApellidos;
    }
    public String getUsrDireccion() {
        return this.usrDireccion;
    }
    
    public void setUsrDireccion(String usrDireccion) {
        this.usrDireccion = usrDireccion;
    }
    public String getUsrIdentificacion() {
        return this.usrIdentificacion;
    }
    
    public void setUsrIdentificacion(String usrIdentificacion) {
        this.usrIdentificacion = usrIdentificacion;
    }
    public Date getUsrFechaNacimiento() {
        return this.usrFechaNacimiento;
    }
    
    public void setUsrFechaNacimiento(Date usrFechaNacimiento) {
        this.usrFechaNacimiento = usrFechaNacimiento;
    }
    public String getUsrTelefono() {
        return this.usrTelefono;
    }
    
    public void setUsrTelefono(String usrTelefono) {
        this.usrTelefono = usrTelefono;
    }
    public String getUsrCorreo() {
        return this.usrCorreo;
    }
    
    public void setUsrCorreo(String usrCorreo) {
        this.usrCorreo = usrCorreo;
    }
    public String getUsrFoto() {
        return this.usrFoto;
    }
    
    public void setUsrFoto(String usrFoto) {
        this.usrFoto = usrFoto;
    }
    public Date getUsrFechaCreacion() {
        return this.usrFechaCreacion;
    }
    
    public void setUsrFechaCreacion(Date usrFechaCreacion) {
        this.usrFechaCreacion = usrFechaCreacion;
    }
    public Date getUsrFechaMod() {
        return this.usrFechaMod;
    }
    
    public void setUsrFechaMod(Date usrFechaMod) {
        this.usrFechaMod = usrFechaMod;
    }
    public Set<UsuarioAcceso> getUsuarioAccesos() {
        return this.usuarioAccesos;
    }
    
    public void setUsuarioAccesos(Set<UsuarioAcceso> usuarioAccesos) {
        this.usuarioAccesos = usuarioAccesos;
    }




}


