package ec.edu.saltos.modelo;
// Generated 18-ago-2020 23:39:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioAcceso generated by hbm2java
 */
public class UsuarioAcceso  implements java.io.Serializable {


     private Integer idUsuarioAcceso;
     private ConfigClave configClave;
     private Persona persona;
     private String usrAccesoNombre;
     private String usrAccesoClave;
     private Integer usrAccesoIntentosfallidos;
     private String usrAccesoEstatus;
     private Date usrAccesoFechaMod;
     private Set<AsignarPerfil> asignarPerfils = new HashSet<AsignarPerfil>(0);
     private Set<Bitacora> bitacoras = new HashSet<Bitacora>(0);

    public UsuarioAcceso() {
    }

    public UsuarioAcceso(ConfigClave configClave, Persona persona, String usrAccesoNombre, String usrAccesoClave, Integer usrAccesoIntentosfallidos, String usrAccesoEstatus, Date usrAccesoFechaMod, Set<AsignarPerfil> asignarPerfils, Set<Bitacora> bitacoras) {
       this.configClave = configClave;
       this.persona = persona;
       this.usrAccesoNombre = usrAccesoNombre;
       this.usrAccesoClave = usrAccesoClave;
       this.usrAccesoIntentosfallidos = usrAccesoIntentosfallidos;
       this.usrAccesoEstatus = usrAccesoEstatus;
       this.usrAccesoFechaMod = usrAccesoFechaMod;
       this.asignarPerfils = asignarPerfils;
       this.bitacoras = bitacoras;
    }
   
    public Integer getIdUsuarioAcceso() {
        return this.idUsuarioAcceso;
    }
    
    public void setIdUsuarioAcceso(Integer idUsuarioAcceso) {
        this.idUsuarioAcceso = idUsuarioAcceso;
    }
    public ConfigClave getConfigClave() {
        return this.configClave;
    }
    
    public void setConfigClave(ConfigClave configClave) {
        this.configClave = configClave;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getUsrAccesoNombre() {
        return this.usrAccesoNombre;
    }
    
    public void setUsrAccesoNombre(String usrAccesoNombre) {
        this.usrAccesoNombre = usrAccesoNombre;
    }
    public String getUsrAccesoClave() {
        return this.usrAccesoClave;
    }
    
    public void setUsrAccesoClave(String usrAccesoClave) {
        this.usrAccesoClave = usrAccesoClave;
    }
    public Integer getUsrAccesoIntentosfallidos() {
        return this.usrAccesoIntentosfallidos;
    }
    
    public void setUsrAccesoIntentosfallidos(Integer usrAccesoIntentosfallidos) {
        this.usrAccesoIntentosfallidos = usrAccesoIntentosfallidos;
    }
    public String getUsrAccesoEstatus() {
        return this.usrAccesoEstatus;
    }
    
    public void setUsrAccesoEstatus(String usrAccesoEstatus) {
        this.usrAccesoEstatus = usrAccesoEstatus;
    }
    public Date getUsrAccesoFechaMod() {
        return this.usrAccesoFechaMod;
    }
    
    public void setUsrAccesoFechaMod(Date usrAccesoFechaMod) {
        this.usrAccesoFechaMod = usrAccesoFechaMod;
    }
    public Set<AsignarPerfil> getAsignarPerfils() {
        return this.asignarPerfils;
    }
    
    public void setAsignarPerfils(Set<AsignarPerfil> asignarPerfils) {
        this.asignarPerfils = asignarPerfils;
    }
    public Set<Bitacora> getBitacoras() {
        return this.bitacoras;
    }
    
    public void setBitacoras(Set<Bitacora> bitacoras) {
        this.bitacoras = bitacoras;
    }




}


